Repository ApollosProject/apollos-apps, pull requests merged in 2018-08, with the labels that each got.

#176 Fix infinite splashscreen in storybook
  mobile/App.js
  mobile/src/client/index.js
Labels: ready for review

#197 136 Discover Feed
  api/src/data/content-channels/model.js
  api/src/data/content-items/__tests__/__snapshots__/model.tests.js.snap
  api/src/data/content-items/model.js
Labels: ready for review

#195 161 Adding individual devos to the home feed
  api/src/data/content-items/model.js
Labels: merge

#200 Testing support for Apollo Datasources
  api/__mocks__/apollo-datasource-mocks/index.js
  api/__mocks__/apollo-datasource-mocks/live-stream.js
  api/__mocks__/apollo-server-env.js
  api/src/data/live/__tests__/__snapshots__/resolver.tests.js.snap
  api/src/data/live/__tests__/resolver.tests.js
  api/src/getDataSources.js
  api/src/index.js
  api/src/utils/testUtils.js
Labels: merge

#177 updated to v0.4.0
  .github/PULL_REQUEST_TEMPLATE.md
  api/package.json
  mobile/android/app/build.gradle
  mobile/ios/apollos-church-app-tvOS/Info.plist
  mobile/ios/apollos-church-app-tvOSTests/Info.plist
  mobile/ios/apollos-church-app.xcodeproj/project.pbxproj
  mobile/ios/apollos-church-app.xcodeproj/xcshareddata/xcschemes/apollos-church-app-tvOS.xcscheme
  mobile/ios/apollos-church-app.xcodeproj/xcshareddata/xcschemes/apollos-church-app.xcscheme
  mobile/ios/apollos-church-app/AppDelegate.h
  mobile/ios/apollos-church-app/AppDelegate.m
  mobile/ios/apollos-church-app/Base.lproj/LaunchScreen.xib
  mobile/ios/apollos-church-app/Images.xcassets/AppIcon.appiconset/Contents.json
  mobile/ios/apollos-church-app/Images.xcassets/Contents.json
  mobile/ios/apollos-church-app/Info.plist
  mobile/ios/apollos-church-app/main.m
  mobile/ios/apollos-church-appTests/Info.plist
  mobile/ios/apollos-church-appTests/apollos-church-appTests.m
  mobile/ios/apolloschurchapp-tvOS/Info.plist
  mobile/ios/apolloschurchapp-tvOSTests/Info.plist
  mobile/ios/apolloschurchapp/Info.plist
  mobile/ios/apolloschurchappTests/Info.plist
  mobile/package.json
  scripts/change-log/append-change-log.js
  scripts/change-log/generate-git-log.sh
  scripts/update-change-log.sh
  scripts/update-mobile-versions.sh
Labels: merge

#199 Sibling Content api
  api/package.json
  api/src/data/content-items/__tests__/__snapshots__/model.tests.js.snap
  api/src/data/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  api/src/data/content-items/__tests__/model.tests.js
  api/src/data/content-items/__tests__/resolvers.tests.js
  api/src/data/content-items/index.js
  api/src/data/content-items/model.js
Labels: merge

#207 Add the ability to share individual pieces of content
  mobile/src/content-single/index.js
  mobile/src/ui/Share/Share.tests.js
  mobile/src/ui/Share/__snapshots__/Share.tests.js.snap
  mobile/src/ui/Share/index.js
  mobile/src/utils/content/share.js
Labels: merge

#204 Created documentation for creating a release within the Apollos Church App
  README.md
  scripts/change-log/generate-git-log.sh
Labels: merge

#209 Add fetch policies to improve data loading from server
  mobile/src/client/authLink.js
  mobile/src/content-feed/index.js
  mobile/src/content-single/index.js
  mobile/src/live/LiveButton.js
  mobile/src/tabs/connect/Connect.js
  mobile/src/tabs/discover/Discover.js
  mobile/src/tabs/home/Home.js
Labels: merge

#210 Remove dependency of API on parent folder structure
  api/.babelrc
Labels: merge

#215 fix the `getLiveStream` query so that the LiveButton shows back up
  mobile/package.json
  mobile/src/live/LiveButton.js
  mobile/src/live/LiveButton.tests.js
  mobile/src/live/getLiveStream.graphql
  mobile/yarn.lock
Labels: ready for review

#202 add media player client-side state
  mobile/src/client/__mocks__/index.js
  mobile/src/store/MediaPlayer.tests.js
  mobile/src/store/__snapshots__/Auth.tests.js.snap
  mobile/src/store/__snapshots__/MediaPlayer.tests.js.snap
  mobile/src/store/index.js
Labels: merge

#198 189 react-native-video
  mobile/android/app/build.gradle
  mobile/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  mobile/android/settings.gradle
  mobile/ios/apolloschurchapp.xcodeproj/project.pbxproj
  mobile/ios/apolloschurchapp/Info.plist
  mobile/jest.setup.js
  mobile/package.json
  mobile/src/content-single/getContentItem.graphql
  mobile/src/content-single/index.js
  mobile/src/ui/VideoPlayer/VideoPlayer.stories.js
  mobile/src/ui/VideoPlayer/VideoPlayer.tests.js
  mobile/src/ui/VideoPlayer/__snapshots__/VideoPlayer.tests.js.snap
  mobile/src/ui/VideoPlayer/index.android.js
  mobile/src/ui/VideoPlayer/index.ios.js
  mobile/src/ui/VideoPlayer/styles.js
  mobile/yarn.lock
Labels: merge

#220 Added Inline Documentation
  README.md
  mobile/src/content-feed/index.js
Labels: merge

#173 Add ability to style content with colors from API
  api/package.json
  api/src/data/content-items/index.js
  api/src/data/index.js
  api/src/data/theme/colorScalarType.js
  api/src/data/theme/index.js
  api/yarn.lock
  mobile/src/auth/index.js
  mobile/src/auth/login/__snapshots__/Form.tests.js.snap
  mobile/src/auth/signup/__snapshots__/Form.tests.js.snap
  mobile/src/content-single/getContentItem.graphql
  mobile/src/content-single/index.js
  mobile/src/tabs/home/Home.js
  mobile/src/ui/BackgroundView/index.js
  mobile/src/ui/Button/Button.js
  mobile/src/ui/Button/__snapshots__/Button.tests.js.snap
  mobile/src/ui/Card/__snapshots__/Card.tests.js.snap
  mobile/src/ui/CenteredView/index.js
  mobile/src/ui/Chip/__snapshots__/Chip.tests.js.snap
  mobile/src/ui/FeedItemCard/__snapshots__/FeedItemCard.tests.js.snap
  mobile/src/ui/Share/index.js
  mobile/src/ui/TableView/__snapshots__/TableView.tests.js.snap
  mobile/src/ui/VideoPlayer/index.android.js
  mobile/src/ui/VideoPlayer/index.ios.js
  mobile/src/ui/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  mobile/src/ui/inputs/InputUnderline.js
  mobile/src/ui/inputs/Picker/__snapshots__/Picker.tests.js.snap
  mobile/src/ui/inputs/Picker/index.js
  mobile/src/ui/inputs/Switch/__snapshots__/Switch.tests.js.snap
  mobile/src/ui/inputs/Switch/index.js
  mobile/src/ui/inputs/Text/__snapshots__/Text.tests.js.snap
  mobile/src/ui/styled/__snapshots__/styled.tests.js.snap
  mobile/src/ui/theme/__snapshots__/createTheme.tests.js.snap
  mobile/src/ui/theme/createTheme.js
  mobile/src/ui/theme/createTheme.tests.js
  mobile/src/ui/theme/defaultTheme.js
  mobile/src/ui/theme/types/dark.js
  mobile/src/ui/theme/types/light.js
Labels: merge

#225 Add stories and tests for VideoPlayer overlay
  mobile/src/ui/VideoPlayer/VideoPlayer.stories.js
  mobile/src/ui/VideoPlayer/VideoPlayer.tests.js
  mobile/src/ui/VideoPlayer/__snapshots__/VideoPlayer.tests.js.snap
Labels: ready for review

#229 Fix appcenter builds
  packages/apolloschurchapp/appcenter-post-clone.sh
Labels: 🛑 dont merge

#230 Import Request class from ApolloEnv
  packages/apollos-church-api/src/data/auth/data-source.js
Labels: merge

#231 Babel fixes
  package.json
  packages/apollos-church-api/package.json
  packages/apolloschurchapp/.babelrc
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/auth/LoginButton.js
  packages/apolloschurchapp/src/auth/getAuthToken.graphql
  packages/apolloschurchapp/src/auth/getAuthToken.js
  packages/apolloschurchapp/src/auth/login/authenticate.graphql
  packages/apolloschurchapp/src/auth/login/authenticate.js
  packages/apolloschurchapp/src/auth/login/index.js
  packages/apolloschurchapp/src/auth/logout.graphql
  packages/apolloschurchapp/src/auth/logout.js
  packages/apolloschurchapp/src/auth/signup/index.js
  packages/apolloschurchapp/src/auth/signup/registerPerson.graphql
  packages/apolloschurchapp/src/auth/signup/registerPerson.js
  packages/apolloschurchapp/src/content-feed/content-feed.tests.js
  packages/apolloschurchapp/src/content-feed/getContentFeed.graphql
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-feed/index.js
  packages/apolloschurchapp/src/content-single/getContentItem.graphql
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/content-single/getContentItemMinimalState.graphql
  packages/apolloschurchapp/src/content-single/getContentItemMinimalState.js
  packages/apolloschurchapp/src/content-single/index.js
  packages/apolloschurchapp/src/live/LiveButton.js
  packages/apolloschurchapp/src/live/LiveButton.tests.js
  packages/apolloschurchapp/src/live/getLiveStream.graphql
  packages/apolloschurchapp/src/live/getLiveStream.js
  packages/apolloschurchapp/src/store/__snapshots__/Auth.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/Connect.js
  packages/apolloschurchapp/src/tabs/connect/getLoginState.graphql
  packages/apolloschurchapp/src/tabs/connect/getLoginState.js
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.graphql
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
  packages/apolloschurchapp/src/tabs/discover/Discover.js
  packages/apolloschurchapp/src/tabs/discover/discover.tests.js
  packages/apolloschurchapp/src/tabs/discover/getContentChannels.graphql
  packages/apolloschurchapp/src/tabs/discover/getContentChannels.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.graphql
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/tabs/home/home.tests.js
  packages/babel-preset-apollos/package.json
  yarn.lock
Labels: ready for review

#232 [API] Add Sharing Type w/ Message/Title/URL
  packages/apollos-church-api/src/data/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-church-api/src/data/content-items/__tests__/resolvers.tests.js
  packages/apollos-church-api/src/data/content-items/index.js
  packages/apollos-church-api/src/data/index.js
  packages/apollos-church-api/src/data/media/index.js
  packages/apollos-church-api/src/data/sharable/index.js
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-feed/index.js
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/content-single/index.js
  packages/apolloschurchapp/src/tabs/discover/TileImageItem.js
  packages/apolloschurchapp/src/tabs/discover/getContentChannels.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/utils/content/share.js
Labels: merge

#234 Authorization Header update
  packages/apollos-church-api/src/data/esv/data-source.js
Labels: ready for review

#246 Fix now deploys
  .travis.yml
  package.json
  packages/apollos-church-api/package.json
  packages/babel-preset-apollos/package.json
Labels: merge
