Repository ApollosProject/apollos-apps, pull requests merged in 2019-10, with the labels that each got.

#1077 Adds TTLs throughout the app to speed up repeat Rock requests
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-rock/src/campuses/data-source.js
  packages/apollos-data-connector-rock/src/content-channels/data-source.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/events/data-source.js
  packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
  packages/apollos-rock-apollo-data-source/src/request-builder.js
  yarn.lock
Labels: merge

#1080 Fixes Apple Email Warnings
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
Labels: merge

#1072 Adds Apollos Plugin support to `getCursorByChildContentItemId`
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#1084 Fixes Summary Field
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: ready for review

#1087 Lowers max age of isLive schema
  packages/apollos-data-schema/src/index.js
Labels: ready for review

#1078 Removes Campus Distance from Onboarding Screen
  packages/apollos-ui-kit/src/CampusCard/index.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apolloschurchapp/ios/Podfile.lock
Labels: merge

#1090 Publish Schema to Engine
  packages/apollos-church-api/scripts/generateLocalSchema.sh
Labels: ready for review

#1089 Adds Explicit Apollo Engine Config
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/src/server.js
Labels: merge

#1097 Decodes Feature Text
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-rock-apollo-data-source/src/utils.js
Labels: ready for review

#1098 Refactors Locations in Onboarding
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.tests.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
  packages/apolloschurchapp/ios/Podfile.lock
Labels: merge

#1092 Adds ability for server to pick up REDIS_URL
  packages/apollos-server-core/src/index.js
Labels: merge

#1100 v1.2.0-beta.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1099 Filters Active Group Members
  packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/groups/data-source.js
Labels: ready for review

#1101 Fixes profile image uploading
  packages/apollos-data-connector-rock/src/binary-files/__tests__/__snapshots__/binary-files.tests.js.snap
  packages/apollos-data-connector-rock/src/binary-files/data-source.js
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
Labels: merge

#1093 Adds Redis Cache and stores isLiked / likeCount in RedisCache.
  packages/apollos-apollo-server-env-mock/src/index.js
  packages/apollos-church-api/package.json
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-redis-cache/.babelrc
  packages/apollos-data-connector-redis-cache/.npmignore
  packages/apollos-data-connector-redis-cache/README.md
  packages/apollos-data-connector-redis-cache/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-redis-cache/src/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-redis-cache/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-redis-cache/src/data-source.js
  packages/apollos-data-connector-redis-cache/src/index.js
  packages/apollos-data-connector-rock/src/followings/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/followings/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/followings/data-source.js
  packages/apollos-data-connector-rock/src/followings/resolver.js
  yarn.lock
Labels: merge

#1104 Fix location finder not updating after location permission granted (Android)
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/requestLocation.android.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/requestLocation.ios.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: reviewed

#1105 Fixes occasional expansion of the TabBar (hopefully final fix)
  packages/apollos-ui-media-player/src/MediaPlayer/MediaPlayerSpacer.js
Labels: ready for review

#1102 Filter Unpublished Content
  packages/apollos-church-api/config.yml
  packages/apollos-config/src/__tests__/__snapshots__/yaml-load.tests.js.snap
  packages/apollos-config/src/__tests__/test.yml
  packages/apollos-config/src/__tests__/yaml-load.tests.js
  packages/apollos-config/src/attach-env-variables.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: ready for review

#1103 Adds Rock Token to API
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/auth/__tests__/index.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
  packages/apollos-data-connector-rock/src/auth/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1106 Fixes change password save button hidden
  packages/apolloschurchapp/src/user-settings/ChangePassword.js
  packages/apolloschurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
Labels: merge

#1110 Removes Redis warnings and fixes cache keys for like counts
  packages/apollos-data-connector-redis-cache/src/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-redis-cache/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-redis-cache/src/data-source.js
  packages/apollos-data-connector-rock/src/followings/data-source.js
Labels: merge

#1111 Add translation prop to ScriptureItem component
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.stories.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.tests.js
  packages/apollos-ui-scripture/src/Scripture/__snapshots__/ScriptureItem.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
Labels: merge

#1120 Adds Rock Token to In App Browser
  packages/apolloschurchapp/src/testing-control-panel/index.js
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.js
Labels: merge

#1113 Add Back Navigation to Auth Screens
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/VerificationConnected.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
Labels: merge

#1121 Adds event descriptions
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/events/__tests__/data-source.test.js
  packages/apollos-data-connector-rock/src/events/data-source.js
  packages/apollos-data-connector-rock/src/events/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/event/Event.js
  packages/apolloschurchapp/src/event/EventConnected.tests.js
  packages/apolloschurchapp/src/event/__snapshots__/Event.tests.js.snap
  packages/apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
  packages/apolloschurchapp/src/event/getEvent.js
Labels: merge

#1128 Fixes miniplayer close button
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
Labels: ready for review

#1124 Updates some of theme alpha values to match new Apollos style guide
  packages/apollos-ui-kit/src/ActionBar/__snapshots__/ActionBar.tests.js.snap
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/__snapshots__/ActionListCard.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/__snapshots__/Avatar.tests.js.snap
  packages/apollos-ui-kit/src/Card/CardWrapper/__snapshots__/CardWrapper.tests.js.snap
  packages/apollos-ui-kit/src/Card/ErrorCard/__snapshots__/ErrorCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/MediaThumbnail/__snapshots__/MediaThumbnail.tests.js.snap
  packages/apollos-ui-kit/src/OverlayBackgroundImage/__snapshots__/OverlayBackgroundImage.tests.js.snap
  packages/apollos-ui-kit/src/TableView/__snapshots__/TableView.tests.js.snap
  packages/apollos-ui-kit/src/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Picker/__snapshots__/Picker.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Radio/__snapshots__/Radio.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/types/dark.js
  packages/apollos-ui-kit/src/theme/types/light.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: ready for review

#1129 Removes Caching of Auth Tokens
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.js
Labels: merge

#1122 Adds an active/disabled state to HorizontalHighlightCard
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.stories.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.tests.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
Labels: merge

#1117 Reduce Warnings
  packages/apollos-ui-kit/src/ActionListCard/index.js
  packages/apollos-ui-kit/src/ConnectedImage/index.js
  packages/apollos-ui-kit/src/DefaultCard/index.js
  packages/apollos-ui-kit/src/FeaturedCard/index.js
  packages/apollos-ui-kit/src/MediaQuery/withWindow.js
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/src/Provider.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  yarn.lock
Labels: merge

#1133 Adds LOAD_TESTING documentation
  LOAD_TESTING.md
  doc-images/bm-0.png
  doc-images/bm-1.png
  doc-images/bm-2.png
  doc-images/bm-3.png
  doc-images/bm-4.png
  doc-images/bm-5.png
  load-tests/Apollos App Testing.jmx
Labels: merge

#1130 fix media player titles on android not being centered.
  packages/apollos-ui-media-player/src/MediaPlayer/AirPlayButton.js
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenControls.js
Labels: merge

#1134 Fixes Group members function
  packages/apollos-data-connector-rock/src/groups/data-source.js
Labels: merge

#1135 Highlights the active card in HorizontalContentFeeds
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/index.js
Labels: merge

#1136 Upgrade react native device info
  packages/apollos-ui-analytics/jest.setup.js
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-analytics/src/Analytics.tests.js
  packages/apollos-ui-analytics/src/Provider.js
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: ready for review

#1137 Fix Tappable Areas in Devotional Content Items
  packages/apollos-ui-kit/src/ModalView/ModalViewHeader.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/index.js
  packages/apolloschurchapp/src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
Labels: merge

#1141 Fixes invalid nodes breaking search results.
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-algolia-search/src/resolver.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/index.js
Labels: ready for review

#1094 Prevent Extra Space in Tab Bar
  packages/apollos-ui-media-player/src/MediaPlayer/MediaPlayerSpacer.js
  packages/apollos-ui-media-player/src/tabBarWithMediaSpacer.js
Labels: merge

#1142 v1.2.0-beta.6
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1112 Fixes HTMLView content rendering bugs
  packages/apollos-data-connector-rock/src/sanitize-html.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
  packages/apollos-ui-htmlview/src/HTMLView/index.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-scripture/src/Scripture/ScriptureHTMLView.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
Labels: merge

#1132 Adds "Soft" Hyphenation of HorizontalHighlightCard Item Titles
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/content-feed/content-feed.tests.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeedConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/DiscoverFeed.tests.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/SearchFeed.tests.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/discover.tests.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/ui/ContentCardConnected/query.js
  packages/apolloschurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
  yarn.lock
Labels: merge, reviewed

#1146 Improves consistency of tab view fix
  packages/apollos-ui-kit/src/TabView/index.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/index.js
Labels: merge

#1143 makes markers tappable, campuses tappable, and always show current campus first
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/Marker.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/getCampusLocations.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: merge

#1147 Include items from Channels that don't require approval
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#1148 Adds Version Number
  packages/apolloschurchapp/src/user-settings/index.js
Labels: merge

#1150 v1.2.0-beta.7
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
  scripts/post-release-tag-update.sh
Labels: merge

#1156 Fixes text theme colors in navigation headers
  packages/apolloschurchapp/src/tabs/connect/index.js
  packages/apolloschurchapp/src/tabs/discover/index.js
Labels: merge

#1154 Hides content feed item when sections are empty
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/TileContentFeed.js
Labels: ready for review

#1162 Adds additional ESLint recommendation to readme
  README.md
Labels: merge

#1163 Location Screen Media Player Spacing
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
Labels: merge

#1165 Fixes Trailing Slash Bug
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.js
Labels: ready for review

#1161 Sets maximum date for date picker
  packages/apollos-ui-kit/src/inputs/DateInput/DateInput.tests.js
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.tests.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
Labels: merge

#1167 Cache coverImages and don't fetch ContentChannels if not needed to reduce home feed query count
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
Labels: merge

#1169 Fixes twilio sid logged on every request
  packages/apollos-data-connector-twilio/src/data-source.js
Labels: ready for review

#1168 Removes like-count from content tile
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: ready for review

#1166 Order Content Channels
  packages/apollos-data-connector-rock/src/content-channels/__tests__/__snapshots__/model.tests.js.snap
  packages/apollos-data-connector-rock/src/content-channels/__tests__/model.tests.js
  packages/apollos-data-connector-rock/src/content-channels/data-source.js
Labels: merge

#1173 Grants `Node.get` the ability to shortcut fetching the data from Rock.
  packages/apollos-data-connector-algolia-search/src/resolver.js
  packages/apollos-data-connector-rock/src/followings/data-source.js
  packages/apollos-data-connector-rock/src/followings/resolver.js
  packages/apollos-server-core/__mocks__/graphql-parse-resolve-info.js
  packages/apollos-server-core/package.json
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/__tests__/model.js
  packages/apollos-server-core/src/node/model.js
  packages/apollos-server-core/src/node/resolver.js
  scripts/watch.js
  yarn.lock
Labels: merge

#1171 Adjusts search feed UI to pull items only from Algolia
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/model.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/getSearchResults.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/index.js
  packages/apolloschurchapp/src/ui/SearchCard/SearchCard.tests.js
  packages/apolloschurchapp/src/ui/SearchCard/__snapshots__/SearchCard.tests.js.snap
  packages/apolloschurchapp/src/ui/SearchCard/index.js
Labels: ready for review

#1172 Clear Algolia Index Before Doing a Full Index.
  packages/apollos-data-connector-algolia-search/__mocks__/algoliasearch.js
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
Labels: merge

#1177 Move Picture Loading Indicator
  packages/apollos-ui-kit/src/Avatar/index.js
Labels: merge
