Repository ApollosProject/apollos-apps, pull requests merged in 2019-12, with the labels that each got.

#1254 Remove willow specific field when creating new users
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1256 Trim Profile Fields
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
Labels: ready for review

#1252 Remove second give link
  packages/apolloschurchapp/src/tabs/connect/ActionTable/index.js
Labels: merge

#1253 Use calendar spinner view on android by default
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/inputs/DateInput/DateInput.stories.js
  packages/apollos-ui-kit/src/inputs/DateInput/DateInput.tests.js
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apolloschurchapp/metro.config.js
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: merge

#1250 Upgrades Analytics Package
  packages/apollos-data-connector-analytics/package.json
  yarn.lock
Labels: merge

#1251 Suppress Back Button Width
  packages/apollos-ui-auth/src/BackButton.js
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
Labels: merge

#1259 Front-load Photo Permissions
  packages/apolloschurchapp/__mocks__/react-native-permissions/index.js
  packages/apolloschurchapp/ios/Podfile
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/user-settings/uploadPhoto.js
  yarn.lock
Labels: merge

#1258 Fixes Campus Parts Error
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
  packages/apolloschurchapp/src/user-settings/getUserPhoto.js
  packages/apolloschurchapp/src/user-settings/uploadPhoto.js
Labels: merge

#1261 Stabilize apollo server versions
  packages/apollos-church-api/src/server.js
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-server-core/package.json
  yarn.lock
Labels: merge, ready for review

#1260 Adds baseBorderRadius value to the defaultTheme
  packages/apollos-ui-auth/src/BackButton.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js
  packages/apollos-ui-kit/src/Button/Button.js
  packages/apollos-ui-kit/src/Card/CardWrapper/index.js
  packages/apollos-ui-kit/src/CardTile/index.js
  packages/apollos-ui-kit/src/OverlayBackgroundImage/index.js
  packages/apollos-ui-kit/src/Placeholder/Line.js
  packages/apollos-ui-kit/src/Placeholder/Media.js
  packages/apollos-ui-kit/src/TileImage/index.js
  packages/apollos-ui-kit/src/inputs/Radio/RadioButtonIndicator.js
  packages/apollos-ui-kit/src/inputs/Radio/__snapshots__/Radio.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/styles.js
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/Seeker/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-passes/src/AddToAppleWalletButton/index.js
  packages/apollos-ui-passes/src/PassView/Barcode.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/TileContentFeed.js
  packages/apolloschurchapp/src/user-settings/Locations/Marker.js
Labels: merge

#1255 Allow During Onboarding the Skipping of Birthdate, Gender, or Both
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/updateUserDetails.js
Labels: merge

#1263 v1.2.5
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1249 Fix Featured Card Loading State
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/index.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: merge

#1265 Updates description style for HorizontalDefaultCard
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
Labels: merge

#1264 Updates the design for ActionListItem
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js
  packages/apollos-ui-kit/src/ActionListCard/__snapshots__/ActionListCard.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: merge

#1269 Fixes auth thrashing
  packages/apolloschurchapp/src/NavigationService.js
  packages/apolloschurchapp/src/client/index.js
  packages/apolloschurchapp/src/user-settings/index.js
Labels: merge

#1266 Push Provider/Consumer/Context
  packages/apollos-ui-notifications/jest.setup.js
  packages/apollos-ui-notifications/src/Provider.js
  packages/apollos-ui-notifications/src/__snapshots__/permissionUtils.tests.js.snap
  packages/apollos-ui-notifications/src/index.js
  packages/apollos-ui-notifications/src/permissionUtils.js
  packages/apollos-ui-notifications/src/permissionUtils.tests.js
  packages/apollos-ui-notifications/src/pushProvider.js
  packages/apollos-ui-notifications/src/store.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotifications.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
  packages/apolloschurchapp/ios/Podfile
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/src/ui/Onboarding/index.js
Labels: merge

#1257 Changes Links to Relative Paths
  .eslintrc.js
  packages/apolloschurchapp/src/content-feed/content-feed.tests.js
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-feed/index.js
  packages/apolloschurchapp/src/content-single/ActionContainer/ActionContainer.tests.js
  packages/apolloschurchapp/src/content-single/ActionContainer/index.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/HorizontalContentFeed.tests.js
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/event/Event.tests.js
  packages/apolloschurchapp/src/event/EventConnected.tests.js
  packages/apolloschurchapp/src/scripture/ScriptureConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/ActionBar.js
  packages/apolloschurchapp/src/tabs/connect/ActionTable/index.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/LikedContentList.tests.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.tests.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeedConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/getLikedContent.js
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
  packages/apolloschurchapp/src/tabs/connect/index.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/getContentChannels.js
  packages/apolloschurchapp/src/tabs/discover/discover.tests.js
  packages/apolloschurchapp/src/tabs/discover/index.js
  packages/apolloschurchapp/src/tabs/home/getCampaignContentItem.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/tabs/home/home.tests.js
  packages/apolloschurchapp/src/testing-control-panel/TouchableCell.tests.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
  packages/apolloschurchapp/src/ui/LandingScreen/LandingScreen.tests.js
  packages/apolloschurchapp/src/ui/LikeContentButton/Like.tests.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/LikeButton.tests.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/index.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/updateLikedContent.js
  packages/apolloschurchapp/src/ui/SearchCard/SearchCard.tests.js
  packages/apolloschurchapp/src/ui/SearchInputHeader/SearchInputHeader.tests.js
  packages/apolloschurchapp/src/ui/ShareContentButton/index.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/ShareContentButtonConnected.tests.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/index.js
  packages/apolloschurchapp/src/ui/WebBrowser/index.tests.js
  packages/apolloschurchapp/src/user-settings/ChangePassword.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/PersonDetails.tests.js
  packages/apolloschurchapp/src/user-settings/UserSettings.tests.js
  packages/apolloschurchapp/src/user-settings/index.js
Labels: merge

#1270 New Auth Flow API
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/index.js
  packages/apollos-data-connector-rock/src/auth-sms/data-source.js
  packages/apollos-data-connector-rock/src/auth-sms/resolver.js
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/utils.js
  packages/apollos-data-schema/src/index.js
Labels: merge
