Repository ApollosProject/apollos-apps, pull requests merged in 2019-06, with the labels that each got.

#756 add fetchMoreResolver and working pagination
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-feed/index.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/index.js
  packages/apolloschurchapp/src/tabs/connect/getLikedContent.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/utils/fetchMoreResolver.js
Labels: ready for review, 🛑 dont merge

#760 Renames mergeSchema into the more accurate mergeResolvers
  packages/apollos-data-connector-rock/README.md
  packages/apollos-server-core/src/index.js
  packages/apollos-server-core/src/utils/__tests__/index.tests.js
  packages/apollos-server-core/src/utils/index.js
Labels: ready for review

#761 Release v0.8.7
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#763 Sets storybook access to public
  packages/apollos-ui-storybook/package.json
Labels: ready for review

#759 Adds GraphQL Schema Diff and Linting
  .eslintrc.js
  .graphqlconfig
  .travis.yml
  package.json
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/package.json
  packages/apollos-church-api/schema.graphql
  packages/apollos-church-api/scripts/generateLocalSchema.sh
  packages/apollos-church-api/scripts/schemaDiff.sh
  yarn.lock
Labels: ready for review

#775 Adds Component prop to ConnectedComponents in Onboarding
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskName/AskNameConnected.js
  packages/apollos-ui-onboarding/src/slides/AskName/AskNameConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/Features/FeaturesConnected.js
  packages/apollos-ui-onboarding/src/slides/Features/FeaturesConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/Features/__snapshots__/FeaturesConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
Labels: ready for review

#772 Fixes Google Maps Issue
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml
Labels: ready for review

#762 Corrects the coordinates being sent to LocationFinder query
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: merge

#799 Updates Device Info Package
  packages/apollos-ui-analytics/package.json
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: merge

#791 Fixes Save Button to Follow Keyboard
  packages/apolloschurchapp/src/user-settings/PersonalDetails.js
  packages/apolloschurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
Labels: ready for review

#805 Fixes Parent Image Algorithm
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#810 Fixes not being able to close the check in screen
  packages/apollos-ui-passes/src/index.js
Labels: ready for review

#812 Fixes rock-apollo-datasource null bug
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-rock-apollo-data-source/src/__tests__/data-source.tests.js
  packages/apollos-rock-apollo-data-source/src/index.js
Labels: ready for review

#818 Update onesignal
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: ready for review

#787 Remove required flag from certain schema attributes
  packages/apollos-church-api/local.graphql
  packages/apollos-data-schema/src/index.js
Labels: merge

#786 Don't login a user if their phone number has multiple users
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/index.js
  packages/apollos-data-connector-rock/src/auth-sms/data-source.js
Labels: ready for review

#813 Adds Features boilerplate schema/resolvers/datasource
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-connector-rock/src/features/index.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#825 Sets new phone numbers in SMS Auth as Mobile phone numbers
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/auth-sms/data-source.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
Labels: merge

#784 Willow Required Onboarding Changes
  UPDATING.md
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  packages/apollos-ui-kit/src/inputs/Radio/RadioButtonIndicator.js
  packages/apollos-ui-onboarding/src/OnboardingSwiper/__snapshots__/OnboardingSwiper.tests.js.snap
  packages/apollos-ui-onboarding/src/OnboardingSwiper/index.js
  packages/apollos-ui-onboarding/src/Slide/Slide.js
  packages/apollos-ui-onboarding/src/Slide/SlideContent/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
Labels: merge

#826 Adds Onboarding Test Coverage
  packages/apolloschurchapp/src/ui/Onboarding/Onboarding.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
Labels: ready for review

#816 Adds Today Actions with Persona Feed algorithm
  package.json
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/index.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
  scripts/watch.js
  yarn.lock
Labels: merge

#822 Redesigns Android Location Markers
  packages/apollos-data-connector-rock/src/binary-files/data-source.js
  packages/apollos-data-connector-rock/src/binary-files/resolver.js
  packages/apollos-data-connector-rock/src/campuses/data-source.js
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/Marker.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: merge

#788 Refactors UI Auth package to be more customizable and modular
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/SMS/PhoneEntry.js
  packages/apollos-ui-auth/src/SMS/PhoneEntry.stories.js
  packages/apollos-ui-auth/src/SMS/PhoneEntry.tests.js
  packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/Verification.stories.js
  packages/apollos-ui-auth/src/SMS/Verification.tests.js
  packages/apollos-ui-auth/src/SMS/VerificationConnected.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntry.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
  packages/apollos-ui-auth/src/SMS/index.js
  packages/apollos-ui-auth/src/SMS/requestPin.js
  packages/apollos-ui-auth/src/SMS/verifyPin.js
  packages/apollos-ui-auth/src/index.js
  packages/apollos-ui-auth/src/styles.js
  packages/apollos-ui-auth/src/testUtils.js
Labels: merge

#831 Release v1.0.0
  CHANGELOG.md
  lerna.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
Labels: ready for review

#828 Adds ActionList algorithm driven by a content channel
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
Labels: ready for review

#833 Adds TextFeature resolver/schema/dataSource
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
Labels: ready for review

#832 Fixes publish of packages that had 0 changes in 1.0
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge
