Repository ApollosProject/apollos-apps, pull requests merged in 2019-04, with the labels that each got.

#586 Makes Android Development Smoother
  packages/apolloschurchapp/package.json
Labels: merge

#612 [Onboarding] Adds ConnectedAskName Components to Onboarding
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskNameConnected.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskNameConnected.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/updateUserName.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
  packages/apolloschurchapp/storybook/.babelrc
  yarn.lock
Labels: merge

#613 [OnBoarding] Adds Connected AboutYou Component
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYouConnected.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYouConnected.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/updateUserDetails.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
  packages/apolloschurchapp/src/utils/testUtils.js
Labels: merge, reviewed

#621 Adds routing from Auth -> Onboarding -> Home
  packages/apollos-ui-auth/src/ProtectedRoute.js
  packages/apollos-ui-auth/src/ProtectedRoute.tests.js
  packages/apollos-ui-auth/src/index.js
  packages/apolloschurchapp/src/auth/index.js
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskNameConnected.js
Labels: ready for review

#622 Fixes date picker being unusable for users with null dates
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
Labels: ready for review

#618 Updates Android Color to Generic Styles
  packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml
  packages/apolloschurchapp/android/app/src/main/res/drawable/background_splash.xml
  packages/apolloschurchapp/android/app/src/main/res/layout/launch_screen.xml
  packages/apolloschurchapp/android/app/src/main/res/values-v21/styles.xml
  packages/apolloschurchapp/android/app/src/main/res/values/colors.xml
Labels: merge

#591 Adds SMS Auth UI
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/Header.js
  packages/apollos-ui-auth/src/Password/Login/Form.js
  packages/apollos-ui-auth/src/Password/Login/Form.stories.js
  packages/apollos-ui-auth/src/Password/Login/Form.tests.js
  packages/apollos-ui-auth/src/Password/Login/__snapshots__/Form.tests.js.snap
  packages/apollos-ui-auth/src/Password/Login/authenticate.js
  packages/apollos-ui-auth/src/Password/Login/index.js
  packages/apollos-ui-auth/src/Password/Signup/Form.js
  packages/apollos-ui-auth/src/Password/Signup/Form.stories.js
  packages/apollos-ui-auth/src/Password/Signup/Form.tests.js
  packages/apollos-ui-auth/src/Password/Signup/__snapshots__/Form.tests.js.snap
  packages/apollos-ui-auth/src/Password/Signup/index.js
  packages/apollos-ui-auth/src/Password/Signup/registerPerson.js
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/Provider.js
  packages/apollos-ui-auth/src/SMS/PhoneEntry.js
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/index.js
  packages/apollos-ui-auth/src/index.js
  packages/apollos-ui-auth/src/styles.js
  packages/apollos-ui-kit/src/inputs/Text/__snapshots__/Text.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Text/index.js
  packages/apolloschurchapp/src/NavigationService.js
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/auth/index.js
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
  packages/apolloschurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
  packages/apolloschurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
  yarn.lock
Labels: merge

#627 Updates the passkit package to latest version
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-passes/src/PassGenerator.js
  packages/apollos-rock-apollo-data-source/src/utils.js
  yarn.lock
Labels: merge

#633 Upgrades Formik
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: ready for review

#632 Add Prayer Icon
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/Icon/icons/Pray.js
  packages/apollos-ui-kit/src/Icon/icons/index.js
Labels: merge

#638 Removes the default/automatic notifications prompt on iOS
  packages/apolloschurchapp/src/notifications/NotificationManager.js
Labels: ready for review

#637 Fixes UX for when users finish onboarding
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/__snapshots__/Slide.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/Slide/index.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotificationsConnected.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotificationsConnected.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
Labels: ready for review

#639 Fixs Chip component prop warning that was noticed on onboarding
  packages/apollos-ui-kit/src/Chip/index.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.js
Labels: merge

#643 v0.8.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#624 Adds Static iOS Launch Images
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Base.lproj/LaunchScreen.xib
  packages/apolloschurchapp/ios/apolloschurchapp/Images.xcassets/Contents.json
  packages/apolloschurchapp/ios/apolloschurchapp/Images.xcassets/splash_bg.imageset/Contents.json
  packages/apolloschurchapp/ios/apolloschurchapp/Images.xcassets/splash_bg.imageset/splash_bg.png
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
Labels: ready for review

#628 Simplifies Switch and Fixes Warnings
  packages/apollos-ui-kit/src/TableView/__snapshots__/TableView.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Switch/__snapshots__/Switch.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Switch/index.js
Labels: ready for review

#653 Removes Warning from Onboarding
  packages/apolloschurchapp/src/Providers.js
Labels: ready for review

#601 Adds Script to Generate Component Docs
  .gitignore
  .travis.yml
  package.json
  packages/apollos-ui-kit/docs/buildDocs.sh
  packages/apollos-ui-kit/docs/generateID.js
  packages/apollos-ui-kit/docs/generateMarkdown.js
  packages/apollos-ui-kit/docs/updateSidebar.sh
  packages/apollos-ui-kit/package.json
  yarn.lock
Labels: needs changes

#603 [Personal Content] Creates featured content in home feed
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-kit/src/CardTile/CardTile.tests.js
  packages/apollos-ui-kit/src/CardTile/__snapshots__/CardTile.tests.js.snap
  packages/apollos-ui-kit/src/ConnectedImage/SkeletonImage.js
  packages/apollos-ui-kit/src/ConnectedImage/index.js
  packages/apollos-ui-kit/src/GradientOverlayImage/index.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/getCampaignContentItem.js
Labels: merge

#666 Fixed Card Tile Test
  packages/apollos-ui-kit/src/CardTile/CardTile.tests.js
  packages/apollos-ui-kit/src/CardTile/__snapshots__/CardTile.tests.js.snap
Labels: merge

#630 Add Text Input Underline Option
  packages/apollos-ui-kit/src/inputs/Text/Text.stories.js
  packages/apollos-ui-kit/src/inputs/Text/Text.tests.js
  packages/apollos-ui-kit/src/inputs/Text/__snapshots__/Text.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Text/index.js
Labels: merge

#658 Release 0.8.3
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#661 Removes Custom Tabs
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  packages/apolloschurchapp/android/settings.gradle
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.android.js
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.ios.js
  yarn.lock
Labels: merge
