Repository ApollosProject/apollos-apps, pull requests merged in 2019-09, with the labels that each got.

#1035 Improves Header Contrast
  packages/apollos-ui-kit/src/ModalView/ModalViewHeader.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
Labels: ready for review

#1039 Configs tests to only run story generation when actually publishing
  package.json
Labels: merge

#1040 Fixes calling removed function
  packages/apolloschurchapp/src/Providers.js
Labels: ready for review

#1038 Fixes Highlight Play Icon
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
Labels: merge

#1046 Fixes onesignal pod not installing
  packages/apollos-ui-notifications/package.json
  packages/apolloschurchapp/appcenter-post-clone.sh
  packages/apolloschurchapp/appcenter-pre-build.sh
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: merge

#1047 Updates Cocoapods to 1.7.5
  packages/apolloschurchapp/ios/Podfile.lock
Labels: merge

#1042 Removes unneeded FeedView padding
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/index.js
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: merge

#1037 Algolia Search
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/package.json
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-algolia-search/.babelrc
  packages/apollos-data-connector-algolia-search/.npmignore
  packages/apollos-data-connector-algolia-search/README.md
  packages/apollos-data-connector-algolia-search/__mocks__/algoliasearch.js
  packages/apollos-data-connector-algolia-search/__mocks__/apollo-server-env.js
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
  packages/apollos-data-connector-algolia-search/src/index.js
  packages/apollos-data-connector-algolia-search/src/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-rock-apollo-data-source/src/cursor.js
  packages/apollos-server-core/src/index.js
  packages/apollos-server-core/src/node/resolver.js
  packages/apollos-server-core/src/pagination/utils.js
  yarn.lock
Labels: merge

#1049 Use apollos plugin to fix max node issues
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-rock-apollo-data-source/src/__tests__/data-source.tests.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: merge

#1056 Fixes Lint Error
  packages/apollos-ui-auth/src/Password/Login/Form.js
  packages/apollos-ui-auth/src/Password/Signup/Form.js
Labels: merge

#1057 Improves testing coverage and performance.
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/client/__mocks__/index.js
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/content-feed/content-feed.tests.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/HorizontalContentFeed.tests.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
  packages/apolloschurchapp/src/scripture/ScriptureConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeedConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/PersonDetails.tests.js
  yarn.lock
Labels: ready for review

#1058 Adjusts Scripture Padding and Legal Text Logic
  packages/apollos-ui-scripture/src/Scripture/ScriptureHTMLView.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.js
  packages/apollos-ui-scripture/src/Scripture/__snapshots__/ScriptureItem.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
Labels: ready for review

#972 Improved In App Browser and Chrome Custom Tabs
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.android.js
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.ios.js
  packages/apolloschurchapp/src/ui/WebBrowser/Browser.js
  packages/apolloschurchapp/src/ui/WebBrowser/index.js
  packages/apolloschurchapp/src/ui/WebBrowser/index.tests.js
  yarn.lock
Labels: merge

#1059 Add action list feed feature for upcoming events
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/resolver.test.js.snap
  packages/apollos-data-connector-rock/src/events/__tests__/data-source.test.js
  packages/apollos-data-connector-rock/src/events/data-source.js
  packages/apollos-data-connector-rock/src/events/resolver.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1051 Installs Pods Automatically
  package.json
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/scripts/install_pods.sh
Labels: ready for review

#1036 Adds spacing to miniplayer controls
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
Labels: merge

#1062 Adds Search indexing and Job Queue
  README.md
  SEARCH.md
  api_heroku.tf
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/src/data/index.js
  packages/apollos-church-api/src/server.js
  packages/apollos-data-connector-algolia-search/__mocks__/algoliasearch.js
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/jobs.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-algolia-search/src/__tests__/jobs.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
  packages/apollos-data-connector-algolia-search/src/index.js
  packages/apollos-data-connector-algolia-search/src/jobs.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-server-core/package.json
  packages/apollos-server-core/src/index.js
  yarn.lock
Labels: reviewed

#1066 Updates Development to iPhone 11 Sim
  packages/apolloschurchapp/package.json
Labels: merge

#939 Adds Groups Functionality to API
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/resolver.test.js.snap
  packages/apollos-data-connector-rock/src/groups/__tests__/data-source.test.js
  packages/apollos-data-connector-rock/src/groups/__tests__/resolver.test.js
  packages/apollos-data-connector-rock/src/groups/data-source.js
  packages/apollos-data-connector-rock/src/groups/index.js
  packages/apollos-data-connector-rock/src/groups/resolver.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
Labels: ready for review

#1068 Adds ability to view events in app
  packages/apollos-church-api/local.graphql
  packages/apollos-church-api/src/data/index.js
  packages/apollos-church-api/src/server.js
  packages/apollos-data-connector-rock/src/events/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/events/__tests__/data-source.test.js
  packages/apollos-data-connector-rock/src/events/__tests__/resolver.test.js
  packages/apollos-data-connector-rock/src/events/data-source.js
  packages/apollos-data-connector-rock/src/events/resolver.js
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/event/Event.js
  packages/apolloschurchapp/src/event/Event.tests.js
  packages/apolloschurchapp/src/event/EventConnected.js
  packages/apolloschurchapp/src/event/EventConnected.tests.js
  packages/apolloschurchapp/src/event/__snapshots__/Event.tests.js.snap
  packages/apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
  packages/apolloschurchapp/src/event/components.js
  packages/apolloschurchapp/src/event/getEvent.js
  packages/apolloschurchapp/src/event/index.js
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/tabs/home/Features/index.js
Labels: merge

#1073 Add Multiple Group Leader Support
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/data-source.test.js.snap
  packages/apollos-data-connector-rock/src/groups/__tests__/__snapshots__/resolver.test.js.snap
  packages/apollos-data-connector-rock/src/groups/__tests__/data-source.test.js
  packages/apollos-data-connector-rock/src/groups/__tests__/resolver.test.js
  packages/apollos-data-connector-rock/src/groups/data-source.js
  packages/apollos-data-connector-rock/src/groups/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge
