Repository ApollosProject/apollos-apps, pull requests merged in 2019-03, with the labels that each got.

#536 Adds Onboarding Scaffold
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/ui/Onboarding/Onboarding.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/__snapshots__/Slide.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/Slide/index.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
  yarn.lock
Labels: ready for review

#574 Adds Gender in Person API
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#582 Removes People (by email) Query
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#575 Adds Person Birth Date
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#577 Exposes getting / updating current campus
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-passes/src/resolver.tests.js
  packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-rock/src/campuses/__tests__/resolver.tests.js
  packages/apollos-data-connector-rock/src/campuses/data-source.js
  packages/apollos-data-connector-rock/src/campuses/resolver.js
  packages/apollos-data-connector-rock/src/family/__tests__/__snapshots__/schema.tests.js.snap
  packages/apollos-data-connector-rock/src/family/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/family/__tests__/schema.tests.js
  packages/apollos-data-connector-rock/src/family/data-source.js
  packages/apollos-data-connector-rock/src/family/index.js
  packages/apollos-data-connector-rock/src/family/resolver.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/template/data-source.tests.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
  packages/apolloschurchapp/src/store/__snapshots__/Auth.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeaderConnected.js
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
Labels: merge

#583 Release v0.8.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
  scripts/change-log/generate-git-log.sh
Labels: ready for review

#584 Fixes user campus not returning location
  packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-rock/src/campuses/__tests__/resolver.tests.js
  packages/apollos-data-connector-rock/src/campuses/data-source.js
Labels: merge

#568 Adds Pagination w/ First and Limit support to the getLikedContent
  UPDATING.md
  packages/apollos-data-connector-rock/src/followings/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/followings/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/followings/data-source.js
  packages/apollos-data-connector-rock/src/followings/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/LikedContentList.tests.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeedConnected.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeedConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/getLikedContent.js
  packages/apolloschurchapp/src/ui/LikeButton/updateLikedContent.js
Labels: merge

#585 Adds support for Node to use Interface's DataModel instead of relying on Aliases
  README.md
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/followings/data-source.js
  packages/apollos-data-connector-rock/src/followings/resolver.js
  packages/apollos-server-core/package.json
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/__tests__/model.js
  packages/apollos-server-core/src/node/__tests__/resolver.js
  packages/apollos-server-core/src/node/model.js
  packages/apollos-server-core/src/node/resolver.js
Labels: merge

#587 Protects fields person resolver from access by non-current person
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/index.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
  packages/apollos-data-connector-rock/src/campuses/resolver.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-data-connector-rock/src/utils.js
Labels: merge

#578 Adds Onboarding notifications screen
  .travis.yml
  packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/notifications/NotificationManager.js
  packages/apolloschurchapp/src/notifications/__snapshots__/permissionUtils.tests.js.snap
  packages/apolloschurchapp/src/notifications/index.js
  packages/apolloschurchapp/src/notifications/permissionUtils.js
  packages/apolloschurchapp/src/notifications/permissionUtils.tests.js
  packages/apolloschurchapp/src/store/__snapshots__/Auth.tests.js.snap
  packages/apolloschurchapp/src/store/index.js
  packages/apolloschurchapp/src/ui/MediaPlayer/FullscreenPlayer.tests.js
  packages/apolloschurchapp/src/ui/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/Slide.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/Slide/__snapshots__/Slide.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/Slide/index.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/AskName.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskName/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotifications.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotifications.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotifications.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotificationsConnected.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/AskNotificationsConnected.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/__snapshots__/AskNotifications.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
  packages/apolloschurchapp/src/utils/testUtils.js
Labels: merge

#595 Adds `getPersonByAliasId` method on Person dataSource
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
Labels: ready for review

#579 Adds App Splash Screen
  packages/apolloschurchapp/ios/apolloschurchapp/main.m
  packages/apolloschurchapp/src/ui/Splash/Splash.stories.js
  packages/apolloschurchapp/src/ui/Splash/Splash.tests.js
  packages/apolloschurchapp/src/ui/Splash/__snapshots__/Splash.tests.js.snap
  packages/apolloschurchapp/src/ui/Splash/index.js
Labels: merge

#580 Adds Onboarding "Features" Screen
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/Features/Features.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/Features/Features.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/Features/__snapshots__/Features.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/Features/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
Labels: merge

#597 Adds Radio Exports, Tests, and Stories
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/inputs/Radio/Radio.js
  packages/apollos-ui-kit/src/inputs/Radio/Radio.stories.js
  packages/apollos-ui-kit/src/inputs/Radio/Radio.tests.js
  packages/apollos-ui-kit/src/inputs/Radio/RadioButton.js
  packages/apollos-ui-kit/src/inputs/Radio/RadioButtonIndicator.js
  packages/apollos-ui-kit/src/inputs/Radio/__snapshots__/Radio.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Radio/index.js
  packages/apollos-ui-kit/src/inputs/index.js
Labels: merge

#527 Creates MapView Component
  packages/apollos-ui-kit/src/Button/Button.js
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/Chip/__snapshots__/Chip.tests.js.snap
  packages/apollos-ui-kit/src/ThumbnailCard/index.js
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/AndroidManifest.xml
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  packages/apolloschurchapp/android/settings.gradle
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/__snapshots__/AskNotifications.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/CampusCard.js
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/Marker.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/campusChange.js
  packages/apolloschurchapp/src/user-settings/Locations/getCampusLocations.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
  packages/apolloschurchapp/src/user-settings/__snapshots__/UserSettings.tests.js.snap
  packages/apolloschurchapp/src/user-settings/index.js
  yarn.lock
Labels: question, ready for review

#599 Adds testing control panel access to Onboarding
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/onboarding/index.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
Labels: ready for review

#547 Update ButtonIcon to support style prop
  packages/apollos-ui-kit/src/Button/ButtonIcon/ButtonIcon.stories.js
  packages/apollos-ui-kit/src/Button/ButtonIcon/ButtonIcon.test.js
  packages/apollos-ui-kit/src/Button/ButtonIcon/__snapshots__/ButtonIcon.test.js.snap
  packages/apollos-ui-kit/src/Button/ButtonIcon/index.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
  packages/apolloschurchapp/src/ui/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
Labels: merge

#600 undo mounting graphql at root to fix pass generation
  packages/apollos-church-api/src/server.js
Labels: bug, ready for review

#581 Adds Onboarding About You Screen
  packages/apollos-ui-kit/src/inputs/Radio/Radio.stories.js
  packages/apollos-ui-kit/src/inputs/Radio/Radio.tests.js
  packages/apollos-ui-kit/src/inputs/Radio/RadioButton.js
  packages/apollos-ui-kit/src/inputs/Radio/__snapshots__/Radio.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.stories.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/AboutYou.tests.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/slides/AboutYou/index.js
  packages/apolloschurchapp/src/ui/Onboarding/slides/index.js
Labels: merge

#605 Added Update to Location Mutation
  packages/apolloschurchapp/src/user-settings/Locations/campusChange.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: question, ready for review

#607 Release v0.8.1
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#608 add new issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: merge
