Repository ApollosProject/apollos-apps, pull requests merged in 2019-08, with the labels that each got.

#961 Adds DefaultCard and deprecates ContentCard
  packages/apollos-ui-kit/src/ContentCard/index.js
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.stories.js
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.tests.js
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/index.js
Labels: merge

#963 Adds Navigating to auth when logging out
  packages/apolloschurchapp/src/tabs/connect/Connect.js
  packages/apolloschurchapp/src/user-settings/index.js
Labels: merge

#966 Simplifies Feature Content Sources
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: ready for review

#969 Fixes wrong birthdate showing up in the datepicker.
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.tests.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.tests.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
Labels: merge

#962 Fixes wrong campus being selected under certain conditions
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
Labels: merge

#968 Adds Sharing to the Scripture Feature
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
Labels: merge

#965 Adds HorizontalDefaultCard
  packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.stories.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.tests.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
  packages/apollos-ui-kit/src/index.js
Labels: merge

#971 Fixes not being able to reach logout button on small screen sizes
  packages/apolloschurchapp/src/user-settings/index.js
Labels: merge

#970 Fixes Back/Close doing the same thing inside devotionals
  packages/apolloschurchapp/src/content-single/NavigationHeader.js
Labels: merge

#978 Fix using first instead of top in sermon children algorithm
  packages/apollos-data-connector-rock/src/features/data-source.js
Labels: merge

#977 Removes Duplicate Storybook Dependency
  packages/apolloschurchapp/package.json
Labels: merge

#935 Refactor Share Buttons
  packages/apollos-church-api/local.graphql
  packages/apolloschurchapp/src/client/fragmentTypes.json
  packages/apolloschurchapp/src/content-single/ActionContainer/index.js
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
  packages/apolloschurchapp/src/ui/LikeContentButton/Like.tests.js
  packages/apolloschurchapp/src/ui/LikeContentButton/__snapshots__/Like.tests.js.snap
  packages/apolloschurchapp/src/ui/LikeContentButton/index.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/LikeButton.tests.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/getLikedContentItem.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/index.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/updateLikeEntity.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/updateLikedContent.js
  packages/apolloschurchapp/src/ui/ShareButton/getShareContent.js
  packages/apolloschurchapp/src/ui/ShareContentButton/ShareContentButton.tests.js
  packages/apolloschurchapp/src/ui/ShareContentButton/__snapshots__/ShareContentButton.tests.js.snap
  packages/apolloschurchapp/src/ui/ShareContentButton/index.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/ShareContentButtonConnected.tests.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/__snapshots__/ShareContentButtonConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/getShareContent.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/index.js
Labels: merge

#967 Adds HorizontalContentCardConnected and Component prop to ContentCardConnected
  packages/apollos-ui-kit/src/GradientOverlayImage/index.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
  packages/apollos-ui-kit/src/HorizontalTileFeed/__snapshots__/HorizontalTileFeed.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalTileFeed/__snapshots__/TileFeed.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalTileFeed/index.js
  packages/apollos-ui-kit/src/index.js
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/TileContentFeed.js
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/getContentChannels.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/contentCardComponentMapper.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/query.js
  packages/apolloschurchapp/src/ui/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
  packages/apolloschurchapp/src/ui/HorizontalContentCardConnected/index.js
Labels: merge

#976 Adds Sharable Features
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/content-channels/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-connector-rock/src/sharable/index.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
Labels: merge

#928 Content single styles
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/MediaThumbnail/Icon.js
  packages/apollos-ui-kit/src/MediaThumbnail/Item.js
  packages/apollos-ui-kit/src/MediaThumbnail/MediaThumbnail.stories.js
  packages/apollos-ui-kit/src/MediaThumbnail/MediaThumbnail.tests.js
  packages/apollos-ui-kit/src/MediaThumbnail/__snapshots__/MediaThumbnail.tests.js.snap
  packages/apollos-ui-kit/src/MediaThumbnail/index.js
  packages/apollos-ui-kit/src/StretchyView/Stretchy.js
  packages/apollos-ui-kit/src/StretchyView/__snapshots__/StretchyView.tests.js.snap
  packages/apollos-ui-kit/src/StretchyView/index.js
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/theme/ThemeConsumer.js
  packages/apollos-ui-kit/src/theme/icons/Play.js
  packages/apollos-ui-kit/src/theme/index.js
  packages/apollos-ui-kit/src/typography/H2/__snapshots__/H2.tests.js.snap
  packages/apollos-ui-kit/src/typography/H2/index.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apolloschurchapp/src/content-single/ContentSingle.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/Features/index.js
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/testing-control-panel/__snapshots__/TouchableCell.tests.js.snap
  packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/query.js
Labels: ready for review

#820 Updates React Navigation to v3
  package.json
  packages/apollos-ui-auth/jest.setup.js
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/ProtectedRoute.js
  packages/apollos-ui-auth/src/index.js
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/jest.setup.js
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/jest.setup.js
  packages/apollos-ui-onboarding/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainActivity.java
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  packages/apolloschurchapp/android/settings.gradle
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/metro.config.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/content-single/index.js
  packages/apolloschurchapp/src/index.js
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/discover.tests.js
  packages/apolloschurchapp/src/tabs/index.js
  packages/apolloschurchapp/src/tabs/tabBar.js
  packages/apolloschurchapp/src/ui/LandingScreen/__snapshots__/LandingScreen.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  yarn.lock
Labels: help wanted

#982 Fixes play button spacing and title overflow on miniplayer
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apollos-ui-storybook/src/index.js
Labels: ready for review

#985 Adds Content URL Sharing
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
Labels: ready for review

#983 Adds clarity around current position in devotional list
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-ui-kit/src/CardTile/index.js
  packages/apollos-ui-kit/src/HorizontalTileFeed/index.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/index.js
Labels: merge

#987 Adds easy configuration options for bulletin list.
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
Labels: ready for review

#989 Fixes PassKit label color
  packages/apollos-church-api/wallet-passes/checkin.pass/pass.json
Labels: ready for review

#988 Adds BackgroundView back to onboarding
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/index.js
Labels: merge

#891 Sorts Out Location Finder Buttons
  packages/apollos-ui-auth/__mocks__/@react-native-community/async-storage/index.js
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/Provider.js
  packages/apollos-ui-auth/src/authLink.js
  packages/apollos-ui-notifications/__mocks__/@react-native-community/async-storage/index.js
  packages/apollos-ui-onboarding/__mocks__/@react-native-community/async-storage/index.js
  packages/apollos-ui-onboarding/__mocks__/@react-native-community/geolocation/index.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinderConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/hasLocationPermission.android.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/hasLocationPermission.ios.js
  packages/apolloschurchapp/__mocks__/@react-native-community/async-storage/index.js
  packages/apolloschurchapp/__mocks__/@react-native-community/geolocation/index.js
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  packages/apolloschurchapp/android/settings.gradle
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/client/cache.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
  packages/apolloschurchapp/src/user-settings/Locations/requestLocation.android.js
  packages/apolloschurchapp/src/user-settings/Locations/requestLocation.ios.js
  yarn.lock
Labels: merge

#979 New Connect tab styles
  packages/apollos-ui-kit/src/ActionBar/ActionBar.stories.js
  packages/apollos-ui-kit/src/ActionBar/ActionBar.tests.js
  packages/apollos-ui-kit/src/ActionBar/ActionBarItem.js
  packages/apollos-ui-kit/src/ActionBar/__snapshots__/ActionBar.tests.js.snap
  packages/apollos-ui-kit/src/ActionBar/index.js
  packages/apollos-ui-kit/src/Avatar/Avatar.stories.js
  packages/apollos-ui-kit/src/Avatar/Avatar.tests.js
  packages/apollos-ui-kit/src/Avatar/__snapshots__/Avatar.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/index.js
  packages/apollos-ui-kit/src/Button/ButtonIcon/__snapshots__/ButtonIcon.test.js.snap
  packages/apollos-ui-kit/src/Button/ButtonIcon/index.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/icons/Badge.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/ActionBar.js
  packages/apolloschurchapp/src/tabs/connect/ActionTable/index.js
  packages/apolloschurchapp/src/tabs/connect/Connect.js
  packages/apolloschurchapp/src/tabs/connect/Toolbar.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeader.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeader.test.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeaderConnected.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeaderConnected.tests.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeader.test.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeaderConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/index.js
  packages/apolloschurchapp/src/ui/UserAvatarView/AvatarForm.js
  packages/apolloschurchapp/src/ui/UserAvatarView/UserAvatarView.stories.js
  packages/apolloschurchapp/src/ui/UserAvatarView/index.js
  packages/apolloschurchapp/src/user-settings/ChangeAvatar.js
  packages/apolloschurchapp/src/user-settings/getUserPhoto.js
  packages/apolloschurchapp/src/user-settings/index.js
  packages/apolloschurchapp/src/user-settings/uploadPhoto.js
Labels: merge

#991 Fixes RNCAsyncStorage build issue
  package.json
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
Labels: merge

#993 Use `<HorizontalContentCard />` on Content Item children+siblings
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
Labels: ready for review

#992 Fixes liked content feed rendering the wrong cards
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
Labels: merge

#990 Refactors code into a Features component for the home feed
  packages/apollos-ui-kit/src/ActionListCard/ActionListCard.stories.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListCard.tests.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListItem.stories.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListItem.tests.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js
  packages/apollos-ui-kit/src/ActionListCard/__snapshots__/ActionListCard.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/index.js
  packages/apollos-ui-kit/src/index.js
  packages/apolloschurchapp/src/tabs/home/Features/getFeedFeatures.js
  packages/apolloschurchapp/src/tabs/home/Features/index.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/ui/ContentTableCard/ContentTableCard.stories.js
  packages/apolloschurchapp/src/ui/ContentTableCard/ContentTableCardItem.js
  packages/apolloschurchapp/src/ui/ContentTableCard/ContentTableCardItem.stories.js
  packages/apolloschurchapp/src/ui/ContentTableCard/index.js
Labels: merge

#916 Adds VerticalOffset to KeyboardAvoidingView for Android
  packages/apollos-ui-auth/src/SMS/PhoneEntry.js
  packages/apollos-ui-auth/src/SMS/Verification.js
Labels: merge

#1000 Fixes Discover tab rendering on tablets
  packages/apolloschurchapp/src/tabs/discover/Discover.js
Labels: ready for review

#1016 Fixes bug where sermon algorithm would return an error if current sermon had no children
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#997 Allows Username Login
  packages/apollos-ui-auth/src/Auth.tests.js
  packages/apollos-ui-auth/src/Password/Login/index.js
  packages/apollos-ui-auth/src/Password/Signup/index.js
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/index.js
  packages/apolloschurchapp/src/LandingScreen.js
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/__tests__/LandingScreen.tests.js
  packages/apolloschurchapp/src/__tests__/__snapshots__/LandingScreen.tests.js.snap
  packages/apolloschurchapp/src/__tests__/index.test.js
  packages/apolloschurchapp/src/index.js
Labels: ready for review

#998 Fixes like icon positioning for horizontal cards
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
Labels: merge

#1017 Adds Search input component
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/inputs/Search/Search.stories.js
  packages/apollos-ui-kit/src/inputs/Search/Search.tests.js
  packages/apollos-ui-kit/src/inputs/Search/SearchActions.js
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/index.js
  packages/apollos-ui-kit/src/inputs/Search/styles.js
  packages/apollos-ui-kit/src/inputs/index.js
Labels: reviewed
