Repository ApollosProject/apollos-apps, pull requests merged in 2019-07, with the labels that each got.

#836 Deletes unused schema.graphql file
  packages/apollos-church-api/schema.graphql
Labels: merge

#835 Fixes Android Campus Card Shadow
  packages/apollos-ui-kit/src/CampusCard/index.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: merge

#842 Fixes images within anchors crashing App.
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
Labels: merge

#834 add <ActionCard /> component
  packages/apollos-ui-kit/src/ActionCard/ActionCard.stories.js
  packages/apollos-ui-kit/src/ActionCard/ActionCard.tests.js
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/ActionCard/index.js
  packages/apollos-ui-kit/src/Card/Actions.js
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/CardTile/__snapshots__/CardTile.tests.js.snap
  packages/apollos-ui-kit/src/ChannelLabel/index.js
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: merge

#848 Adds API support for content items to have livestreams
  packages/apollos-church-api/config.yml
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-church-online/src/data-source.js
  packages/apollos-data-connector-church-online/src/resolver.js
  packages/apollos-data-connector-rock/src/content-channels/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: ready for review

#847 Hooks up text feature
  packages/apollos-ui-kit/src/index.js
  packages/apolloschurchapp/src/content-single/ActionContainer/index.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
  packages/apolloschurchapp/src/content-single/Features/getContentItemFeatures.js
  packages/apolloschurchapp/src/content-single/Features/index.js
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/ui/Share/index.js
  packages/apolloschurchapp/src/ui/ShareButton/ShareButton.tests.js
  packages/apolloschurchapp/src/ui/ShareButton/__snapshots__/ShareButton.tests.js.snap
  packages/apolloschurchapp/src/ui/ShareButton/getShareContent.js
  packages/apolloschurchapp/src/ui/ShareButton/index.js
Labels: ready for review

#864 Update to build 64-bit Android versions
  packages/apolloschurchapp/android/app/build.gradle
Labels: merge

#862 Adds `minAspectRatio` and `maxAspectRatio` support to ConnectedImage
  packages/apollos-ui-kit/src/ConnectedImage/ConnectedImage.stories.js
  packages/apollos-ui-kit/src/ConnectedImage/ConnectedImage.tests.js
  packages/apollos-ui-kit/src/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  packages/apollos-ui-kit/src/ConnectedImage/index.js
Labels: ready for review

#865 Allow for custom VideoWindow component and disabling of toggle controls on MediaPlayer
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenPlayer.js
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenPlayer.tests.js
  packages/apollos-ui-media-player/src/MediaPlayer/VideoWindow.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apollos-ui-media-player/src/MediaPlayer/index.js
  packages/apollos-ui-media-player/src/index.js
Labels: merge

#866 Adds Safety Checks to Request Filters
  packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
  packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: merge

#870 Adds utility to handle rock key/value attribute
  packages/apollos-rock-apollo-data-source/src/__tests__/utils.tests.js
  packages/apollos-rock-apollo-data-source/src/index.js
  packages/apollos-rock-apollo-data-source/src/utils.js
Labels: ready for review

#871 Adds ability for Text Feature to use KeyValue attribute in Rock
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-rock-apollo-data-source/src/utils.js
Labels: ready for review

#827 Fixes Image Placeholders
  packages/apollos-ui-passes/src/PassView/PassView.stories.js
  packages/apollos-ui-passes/src/PassView/Thumbnail.js
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apollos-ui-passes/src/PassView/index.js
Labels: merge

#878 v1.1.0-beta.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#881 Updates core Chip component styles
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/Chip/Chip.stories.js
  packages/apollos-ui-kit/src/Chip/Chip.tests.js
  packages/apollos-ui-kit/src/Chip/__snapshots__/Chip.tests.js.snap
  packages/apollos-ui-kit/src/Chip/index.js
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
Labels: ready for review

#885 Fixes action list features having the same id
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/data-source.js
Labels: merge

#873 Adds ability to customize gradient
  packages/apollos-ui-kit/src/BackgroundView/BackgroundView.stories.js
  packages/apollos-ui-kit/src/BackgroundView/index.js
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/GradientOverlayImage/GradientOverlayImage.stories.js
  packages/apollos-ui-kit/src/GradientOverlayImage/GradientOverlayImage.tests.js
  packages/apollos-ui-kit/src/GradientOverlayImage/__snapshots__/GradientOverlayImage.tests.js.snap
  packages/apollos-ui-kit/src/GradientOverlayImage/index.js
  packages/apollos-ui-kit/src/TileImage/__snapshots__/TileImage.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apolloschurchapp/src/theme/theme.js
Labels: merge, question

#886 Adds algorithm to ActionListCard to view content from the sermon throughout the week.
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
Labels: merge

#867 Adds FeaturedCard component
  packages/apollos-ui-kit/src/Button/Button.js
  packages/apollos-ui-kit/src/Card/Card.stories.js
  packages/apollos-ui-kit/src/Card/Card.tests.js
  packages/apollos-ui-kit/src/Card/Label.js
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/Card/index.js
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.stories.js
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.tests.js
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/index.js
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/icons/LiveDot.js
  packages/apollos-ui-kit/src/theme/icons/PlaySolid.js
  packages/apollos-ui-kit/src/theme/icons/index.js
Labels: blocked, ready for review

#893 Fixes CardWrapper and Icon loading states
  packages/apollos-ui-kit/src/Card/CardWrapper/index.js
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/Icon/Icon.js
  packages/apollos-ui-kit/src/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeader.test.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: ready for review

#892 Adds scripture feature schema/resolver/datasource
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
Labels: ready for review

#895 Adds UI-Kit export for FeaturedCard
  packages/apollos-ui-kit/src/index.js
Labels: merge

#915 Adds 100% Test Coverage to Config Package
  packages/apollos-config/src/__tests__/__snapshots__/js-load.tests.js.snap
  packages/apollos-config/src/__tests__/js-load.tests.js
  packages/apollos-config/src/__tests__/yaml-load.tests.js
Labels: ready for review

#896 add scripture story for ActionCard
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.stories.js
Labels: merge

#910 fix minor bugs in CardWrapper component
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/CardWrapper/__snapshots__/CardWrapper.tests.js.snap
  packages/apollos-ui-kit/src/Card/CardWrapper/index.js
  packages/apollos-ui-kit/src/Card/ErrorCard/__snapshots__/ErrorCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: merge

#917 Adds 100% Coverage to Share Function
  packages/apolloschurchapp/src/utils/content/__tests__/share.tests.js
Labels: ready for review

#912 Adds Check Against Short Content Summaries
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#902 Removes Unneccesary Native Code
  packages/apolloschurchapp/android/app/src/main/res/values/styles.xml
Labels: merge

#924 Adds Token Check
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#925 Upgrade to RN 0.59.10
  packages/apollos-church-api/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/build.gradle
  packages/apolloschurchapp/android/gradle/wrapper/gradle-wrapper.properties
  packages/apolloschurchapp/android/gradlew
  packages/apolloschurchapp/android/gradlew.bat
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: merge

#907 Adds <StretchyView /> component
  packages/apollos-ui-kit/src/StretchyView/Stretchy.js
  packages/apollos-ui-kit/src/StretchyView/StretchyView.stories.js
  packages/apollos-ui-kit/src/StretchyView/StretchyView.tests.js
  packages/apollos-ui-kit/src/StretchyView/__snapshots__/StretchyView.tests.js.snap
  packages/apollos-ui-kit/src/StretchyView/index.js
Labels: merge

#923 Adds ScriptureFeature to ContentItem feature
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/getContentItemFeatures.js
  packages/apolloschurchapp/src/content-single/Features/index.js
Labels: merge

#922 Adds BodySmall component
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/typography/BodySmall/BodySmall.stories.js
  packages/apollos-ui-kit/src/typography/BodySmall/BodySmall.tests.js
  packages/apollos-ui-kit/src/typography/BodySmall/__snapshots__/BodySmall.tests.js.snap
  packages/apollos-ui-kit/src/typography/BodySmall/index.js
  packages/apollos-ui-kit/src/typography/index.js
Labels: merge

#929 Standardizes FeaturedCard, HighlightCard, and ContentCard prop naming
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.stories.js
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.tests.js
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/index.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.stories.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.tests.js
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/index.js
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/theme/icons/PlayOpaque.js
  packages/apollos-ui-kit/src/theme/icons/index.js
Labels: merge

#921 Adds 100% Coverage for User Web Browser
  packages/apolloschurchapp/src/user-web-browser/Provider.js
  packages/apolloschurchapp/src/user-web-browser/__tests__/BrowserWithUserCookie.tests.js
  packages/apolloschurchapp/src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
  packages/apolloschurchapp/src/user-web-browser/index.js
Labels: merge

#930 Adds HorizontalHighlightCard
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.stories.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.tests.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
Labels: merge

#918 Tests App Utils Functions
  packages/apolloschurchapp/src/utils/__tests__/__snapshots__/utils.tests.js.snap
  packages/apolloschurchapp/src/utils/__tests__/utils.tests.js
  packages/apolloschurchapp/src/utils/fetchMoreResolver.js
Labels: merge

#908 Adds `<OverlayBackgroundImage />` component
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/__snapshots__/Avatar.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/ConnectedImage/index.js
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/GradientOverlayImage/index.js
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/OverlayBackgroundImage/OverlayBackgroundImage.stories.js
  packages/apollos-ui-kit/src/OverlayBackgroundImage/OverlayBackgroundImage.tests.js
  packages/apollos-ui-kit/src/OverlayBackgroundImage/__snapshots__/OverlayBackgroundImage.tests.js.snap
  packages/apollos-ui-kit/src/OverlayBackgroundImage/index.js
  packages/apollos-ui-kit/src/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  packages/apollos-ui-kit/src/TileImage/__snapshots__/TileImage.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotifications.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/Features/__snapshots__/Features.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeaderConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/ui/LandingScreen/__snapshots__/LandingScreen.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
Labels: merge

#933 Release v1.1.0 beta.2
  CHANGELOG.md
  lerna.json
  package.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#920 Adjusts Image max size for better onboarding UI
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/index.js
Labels: ready for review

#927 Logs User Out on Auth Error
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/buildErrorLink.js
  packages/apollos-ui-auth/src/index.js
  packages/apolloschurchapp/src/client/index.js
  yarn.lock
Labels: merge

#938 Fixes sharing text feature
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apolloschurchapp/src/ui/ShareButton/index.js
  packages/apolloschurchapp/src/utils/content/__tests__/share.tests.js
  packages/apolloschurchapp/src/utils/content/share.js
Labels: merge

#960 Align ui-passes image to the right
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
  packages/apollos-ui-passes/src/PassView/index.js
Labels: ready for review
