Repository ApollosProject/apollos-apps, pull requests merged in 2019-11, with the labels that each got.

#1182 Makes like icon optional on cards
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.stories.js
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.tests.js
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/index.js
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.stories.js
  packages/apollos-ui-kit/src/FeaturedCard/FeaturedCard.tests.js
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/index.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.stories.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.tests.js
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/index.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.stories.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.tests.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.stories.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/HorizontalHighlightCard.tests.js
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/index.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: ready for review

#1180 Fixes typename not being pulled from node and removes LikeIcon from feeds
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/index.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/__snapshots__/SearchFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/ui/SearchCard/index.js
  packages/apolloschurchapp/src/ui/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
Labels: merge

#1183 Cleans up front-end fragments and removes LikeIcon from FeedView
  packages/apolloschurchapp/src/content-feed/__snapshots__/content-feed.tests.js.snap
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/getHorizontalContent.js
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/RecentlyLikedTileFeed/__snapshots__/RecentlyLikedTileFeedConnected.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/getLikedContent.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/getContentChannels.js
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/getCampaignContentItem.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/query.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/updateLikedContent.js
Labels: ready for review

#1187 Add Configurability for ROCK Analytics
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-analytics/src/data-source.js
Labels: ready for review

#1188 Jobs Board Auth
  packages/apollos-church-api/config.yml
  packages/apollos-server-core/package.json
  packages/apollos-server-core/src/index.js
  yarn.lock
Labels: merge

#1186 Prefetch the Current User
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1185 Adds <b> and <i> tag support to HTMLView
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
Labels: merge

#1190 Update load tests
  load-tests/Apollos App Testing.jmx
Labels: merge

#1189 Fixes Map Zoom to Nothing
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: merge, ready for review

#1194 Enable gif support on Android
  packages/apolloschurchapp/android/app/build.gradle
Labels: merge

#1199 Only try to get the current person if you have a rock cookie
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: ready for review

#1179 Fixes padding issue with close icon when image is not available
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
Labels: merge

#1201 Ensures user feed is cachables
  packages/apollos-data-schema/src/index.js
Labels: ready for review

#1207 Release 1.2.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1203 Optimizes Content Query
  packages/apolloschurchapp/src/content-single/getContentItem.js
Labels: merge

#1205 Increases Miniplayer Button Size
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
Labels: merge

#1209 Mergify
  .mergify.yml
Labels: merge

#1206 Improves Map Bounce
  packages/apolloschurchapp/src/user-settings/Locations/MapView.js
Labels: merge

#1086 Live item polling
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-church-online/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-church-online/src/data-source.js
  packages/apollos-data-connector-church-online/src/resolver.js
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-schema/src/index.js
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/live/LiveButton.js
  packages/apolloschurchapp/src/live/LiveButton.tests.js
  packages/apolloschurchapp/src/live/LiveContext.js
  packages/apolloschurchapp/src/live/__snapshots__/LiveButton.tests.js.snap
  packages/apolloschurchapp/src/live/getLiveContent.js
  packages/apolloschurchapp/src/live/getLiveStream.js
  packages/apolloschurchapp/src/live/index.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/testing-control-panel/ChangeLivestream.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
Labels: merge

#1211 Mergify Will Delete Branch
  .mergify.yml
Labels: merge, ready for review

#1019 Updated Floating Input Label placement
  packages/apollos-ui-auth/src/Password/Login/__snapshots__/Form.tests.js.snap
  packages/apollos-ui-auth/src/Password/Signup/__snapshots__/Form.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntry.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
  packages/apollos-ui-kit/src/inputs/InputAddon.js
  packages/apollos-ui-kit/src/inputs/Text/Text.stories.js
  packages/apollos-ui-kit/src/inputs/Text/__snapshots__/Text.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Text/index.js
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
  packages/apolloschurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
  packages/apolloschurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
Labels: merge

#1214 Adds Client Info in Request Headers
  packages/apollos-church-api/local.graphql
  packages/apolloschurchapp/src/client/index.js
Labels: merge

#1202 Optimizes Live Stream Query
  packages/apollos-data-connector-church-online/src/data-source.js
  packages/apolloschurchapp/src/content-single/MediaControls/getContentMedia.js
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
  packages/apolloschurchapp/src/content-single/getContentItem.js
Labels: merge

#1218 v1.2.3
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1221 Actually logs users with bad cookies out of the app
  packages/apollos-data-connector-rock/src/auth/data-source.js
  packages/apollos-ui-auth/src/buildErrorLink.js
Labels: ready for review

#1225 Adds additional server analytics
  packages/apollos-ui-analytics/src/Provider.js
  packages/apollos-ui-analytics/src/index.js
Labels: merge

#1222 Check for Valid Images When Rendering Campus Cards.
  packages/apollos-ui-kit/src/CampusCard/index.js
Labels: merge

#1227 Fixes auth back button color
  packages/apollos-ui-auth/src/Password/index.js
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
Labels: merge

#1210 Algolia Delta Sync
  packages/apollos-data-connector-algolia-search/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/jobs.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/__tests__/jobs.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
  packages/apollos-data-connector-algolia-search/src/jobs.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#1219 Optimizes Scripture Version
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-bible/src/data-source.js
  packages/apollos-data-connector-bible/src/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1215 Adds Total Count to Paginated Queries
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
  packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js
  packages/apollos-rock-apollo-data-source/src/index.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: merge

#1220 Improves Content Label Default Type
  packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
Labels: merge

#1170 Improved Caching of Content
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/HTMLContent/index.js
Labels: merge

#1229 Handle Links in the HTMLView.
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
  packages/apollos-ui-htmlview/src/HTMLView/index.js
  packages/apolloschurchapp/src/content-single/HTMLContent/index.js
  packages/apolloschurchapp/src/event/Event.js
Labels: merge

#1238 Improves Mergify
  .mergify.yml
Labels: ready for review

#1178 Adds Scripture Selection to Content
  packages/apollos-data-connector-bible/src/data-source.js
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
Labels: merge

#1233 Improves Content Schema Style
  packages/apollos-data-schema/src/index.js
Labels: merge

#1240 Improves the Error Card
  packages/apollos-ui-kit/src/Card/ErrorCard/ErrorCard.stories.js
  packages/apollos-ui-kit/src/Card/ErrorCard/ErrorCard.tests.js
  packages/apollos-ui-kit/src/Card/ErrorCard/__snapshots__/ErrorCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/ErrorCard/index.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
Labels: merge

#1226 Fixes HTMLView placeholder/loading state
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/index.js
  packages/apollos-ui-kit/src/Placeholder/withPlaceholder.js
  packages/apollos-ui-kit/src/typography/Paragraph/Paragraph.stories.js
  packages/apollos-ui-scripture/src/Scripture/__snapshots__/ScriptureItem.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/event/__snapshots__/Event.tests.js.snap
  packages/apolloschurchapp/src/event/__snapshots__/EventConnected.tests.js.snap
  packages/apolloschurchapp/src/scripture/__snapshots__/ScriptureConnected.tests.js.snap
Labels: merge

#1230 Removes Duplicate Copyright Info
  packages/apollos-ui-scripture/src/Scripture/index.js
  packages/apollos-ui-scripture/src/index.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/ScriptureTab.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
Labels: merge

#1242 Render Devotionals That Have No Scripture
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/index.js
Labels: merge

#1245 v1.2.4
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1244 Fixes Mergify
  .mergify.yml
Labels: merge

#1248 Ensures that n+3 redis connections aren't created
  packages/apollos-data-connector-algolia-search/src/__tests__/__snapshots__/jobs.tests.js.snap
  packages/apollos-data-connector-algolia-search/src/jobs.js
Labels: merge
