Repository ApollosProject/apollos-apps, pull requests merged in 2019-05, with the labels that each got.

#669 Update Apollos Data Rock README.md
  packages/apollos-data-connector-rock/README.md
Labels: ready for review

#660 Updates Several RN Packages
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/android/app/src/main/java/com/apolloschurchapp/MainApplication.java
  packages/apolloschurchapp/android/settings.gradle
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  yarn.lock
Labels: merge

#671 unlink react-native-custom-tabs on ios
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
Labels: merge

#663 Adds Script to Debug Travis
  scripts/debugTravis.sh
Labels: blocked, ready for review

#667 Removes Avatar Margin
  packages/apollos-ui-kit/src/Avatar/__snapshots__/Avatar.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/index.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeader.test.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeaderConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/UserAvatarView/AvatarForm.js
Labels: merge

#623 Fixes email field rendering as [Object object] for sms users
  packages/apollos-data-connector-rock/src/people/resolver.js
Labels: merge

#693 Release v0.8.5
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp.xcodeproj/project.pbxproj
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#696 Adds Apollos.json to help improve upgrade tool.
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  scripts/update-apollos-version.js
Labels: merge

#699 Adds binary files datasource
  packages/apollos-church-api/src/data/index.js
  packages/apollos-data-connector-rock/src/binary-files/__tests__/__snapshots__/binary-files.tests.js.snap
  packages/apollos-data-connector-rock/src/binary-files/__tests__/binary-files.tests.js
  packages/apollos-data-connector-rock/src/binary-files/data-source.js
  packages/apollos-data-connector-rock/src/binary-files/index.js
  packages/apollos-data-connector-rock/src/binary-files/resolver.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
Labels: merge

#684 Fixes null scripture crash and devotional tests.
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/index.js
Labels: merge

#701 Fix appcenter
  packages/apolloschurchapp/appcenter-pre-build.sh
Labels: ready for review

#703 Added strategy for canary releases
  .travis.yml
  package.json
Labels: ready for review

#707 Travis deploy script arg can only take a single command
  .travis.yml
Labels: ready for review

#706 Fixes personal devices "post" by providing required rock field
  packages/apollos-data-connector-rock/src/personal-devices/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/personal-devices/data-source.js
Labels: merge

#708 Updates bible.api usage to match current practices
  packages/apollos-apollo-server-env-mock/src/apollo-datasource-mocks/bible.js
  packages/apollos-data-connector-bible/src/data-source.js
Labels: merge

#717 Adds configurability to ChurchOnline URL
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-church-online/src/data-source.js
Labels: ready for review

#715 Include storybook files with NPM release
  package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/.npmignore
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/.npmignore
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
Labels: merge

#720 Cleans up Project
  .travis.yml
  package.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/.envExample
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/.env.dev.storybook
  packages/apolloschurchapp/.env.production
  packages/apolloschurchapp/.npmignore
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
  yarn.lock
Labels: merge

#698 Fixes Content Items back redirecting to Onboarding
  packages/apolloschurchapp/src/ui/Onboarding/index.js
Labels: merge

#723 GetPersonById should return Photo
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
Labels: merge

#721 Update PhoneEntry.js
  packages/apollos-ui-auth/src/SMS/PhoneEntry.js
Labels: ready for review

#730 Updates Liked Count on Home Feed
  packages/apolloschurchapp/src/ui/LikeButton/index.js
  packages/apolloschurchapp/src/ui/LikeButton/updateLikeEntity.js
Labels: ready for review

#719 Makes Campaign Card Clickable
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
Labels: merge

#732 Fixes Liked Content Feed not populating on first like.
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: merge

#728 Fix Android Navigation Header
  package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/ModalView/ModalView.stories.js
  packages/apollos-ui-kit/src/ModalView/ModalView.tests.js
  packages/apollos-ui-kit/src/ModalView/ModalViewHeader.js
  packages/apollos-ui-kit/src/ModalView/ModalViewHeader.tests.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/index.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/content-single/ContentSingle.js
  packages/apolloschurchapp/src/content-single/NavigationHeader.js
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/ui/LandingScreen/__snapshots__/LandingScreen.tests.js.snap
  yarn.lock
Labels: ready for review

#725 Adds Additional Campus Data
  packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-rock/src/campuses/__tests__/resolver.tests.js
  packages/apollos-data-connector-rock/src/campuses/data-source.js
Labels: merge

#734 Fixes software keyboard in storybook
  packages/apollos-ui-storybook/src/index.js
Labels: merge

#737 Fixes bible.api not handling both data and data.passages
  packages/apollos-data-connector-bible/src/data-source.js
Labels: merge

#736 Cleans up dependencies
  packages/apollos-church-api/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: merge

#741 Removes KeyboardAwareScrollView Package
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/Password/Login/Form.js
  packages/apollos-ui-auth/src/Password/Login/__snapshots__/Form.tests.js.snap
  packages/apollos-ui-auth/src/Password/Signup/Form.js
  packages/apollos-ui-auth/src/Password/Signup/__snapshots__/Form.tests.js.snap
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/user-settings/ChangePassword.js
  packages/apolloschurchapp/src/user-settings/PersonalDetails.js
  packages/apolloschurchapp/src/user-settings/__snapshots__/ChangePassword.tests.js.snap
  packages/apolloschurchapp/src/user-settings/__snapshots__/PersonDetails.tests.js.snap
Labels: merge

#724 Fixes Travis Docs Deploy
  .travis.yml
  packages/apollos-ui-kit/docs/buildDocs.sh
  yarn.lock
Labels: merge

#745 Fixes Docs Sidebar Table of Contents
  .travis.yml
  packages/apollos-ui-kit/docs/buildDocs.sh
Labels: ready for review

#743 Adds smarter resetting of Apollo Cache
  packages/apolloschurchapp/.env.production
  packages/apolloschurchapp/src/client/cache.js
Labels: merge

#748 Documents steps to unlock Rock getCurrentPerson endpoint
  ROCK_SETUP.md
  doc-images/cu-step1.png
  doc-images/cu-step2.png
  doc-images/cu-step3.png
  doc-images/cu-step4.png
  doc-images/cu-step5.png
  doc-images/cu-step6.png
  doc-images/cu-step7.png
Labels: merge

#750 Adds Doc Site to README
  README.md
Labels: merge

#751 Fixes Avatar Margin
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeader.test.js.snap
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/__snapshots__/UserAvatarHeaderConnected.tests.js.snap
  packages/apolloschurchapp/src/ui/UserAvatarView/AvatarForm.js
Labels: ready for review

#709 Adds analytics over Onboarding Scenes
  packages/apollos-ui-analytics/README.md
  packages/apollos-ui-analytics/jest.setup.js
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-analytics/src/TrackEventWhenLoaded.tests.js
  packages/apollos-ui-analytics/src/__snapshots__/withTrackOnPress.tests.js.snap
  packages/apollos-ui-analytics/src/index.js
  packages/apollos-ui-analytics/src/testUtils.js
  packages/apollos-ui-analytics/src/withTrackOnPress.js
  packages/apollos-ui-analytics/src/withTrackOnPress.tests.js
  packages/apollos-ui-onboarding/README.md
  packages/apollos-ui-onboarding/jest.setup.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-onboarding/src/Slide/Slide.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYouConnected.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskName/AskNameConnected.js
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotifications.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotificationsConnected.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/__snapshots__/AskNotificationsConnected.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/Features/FeaturesConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/src/ui/Onboarding/Onboarding.stories.js
Labels: merge

#758 Update README.md
  README.md
Labels: merge
