Repository ApollosProject/apollos-apps, pull requests merged in 2020-06, with the labels that each got.

#1470 Pass text primary color to Date Picker to override dark mode.
  packages/apollos-ui-analytics/jest.setup.js
  packages/apollos-ui-auth/jest.setup.js
  packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntry.tests.js.snap
  packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntryConnected.tests.js.snap
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-htmlview/jest.setup.js
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  packages/apollos-ui-mapview/jest.setup.js
  packages/apollos-ui-media-player/jest.setup.js
  packages/apollos-ui-notifications/jest.setup.js
  packages/apollos-ui-onboarding/jest.setup.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
  packages/apollos-ui-passes/jest.setup.js
  packages/apollos-ui-prayer/jest.setup.js
  packages/apollos-ui-scripture/jest.setup.js
  yarn.lock
Labels: merge

#1473 Release 1.4.1
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1474 Integrated universal links
  packages/apollos-server-core/src/index.js
  packages/apollos-server-core/src/universalLinking/__tests__/__snapshots__/universalLinking.tests.js.snap
  packages/apollos-server-core/src/universalLinking/__tests__/universalLinking.tests.js
  packages/apollos-server-core/src/universalLinking/index.js
  packages/apollos-ui-kit/src/NavigationService/index.js
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-notifications/src/Provider.js
Labels: reviewed

#1457 Adds PrayerCard and PrayerInput component
  package.json
  packages/apollos-ui-analytics/jest.setup.js
  packages/apollos-ui-auth/jest.setup.js
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-htmlview/jest.setup.js
  packages/apollos-ui-kit/src/ConnectedImage/__snapshots__/ConnectedImage.tests.js.snap
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/theme/icons/CircleOutlinePlus.js
  packages/apollos-ui-kit/src/theme/icons/index.js
  packages/apollos-ui-mapview/jest.setup.js
  packages/apollos-ui-media-player/jest.setup.js
  packages/apollos-ui-notifications/jest.setup.js
  packages/apollos-ui-onboarding/jest.setup.js
  packages/apollos-ui-passes/jest.setup.js
  packages/apollos-ui-prayer/jest.setup.js
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-prayer/src/PrayerCard/PrayerCard.stories.js
  packages/apollos-ui-prayer/src/PrayerCard/PrayerCard.tests.js
  packages/apollos-ui-prayer/src/PrayerCard/__snapshots__/PrayerCard.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerCard/index.js
  packages/apollos-ui-prayer/src/PrayerInput/PrayerInput.stories.js
  packages/apollos-ui-prayer/src/PrayerInput/PrayerInput.tests.js
  packages/apollos-ui-prayer/src/PrayerInput/__snapshots__/PrayerInput.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerInput/index.js
  packages/apollos-ui-prayer/src/PrayerSwiper/PrayerSwiper.stories.js
  packages/apollos-ui-scripture/jest.setup.js
Labels: merge

#1466 Adds PrayerScreen component
  packages/apollos-ui-prayer/src/PrayerScreen/PrayerScreen.stories.js
  packages/apollos-ui-prayer/src/PrayerScreen/PrayerScreen.tests.js
  packages/apollos-ui-prayer/src/PrayerScreen/__snapshots__/PrayerScreen.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerScreen/index.js
  packages/apollos-ui-prayer/src/PrayerSwiper/PrayerSwiper.stories.js
Labels: merge, reviewed

#1464 Adds PrayerFeature ui
  packages/apollos-ui-kit/src/Icon/__snapshots__/Icon.tests.js.snap
  packages/apollos-ui-kit/src/theme/icons/Plus.js
  packages/apollos-ui-kit/src/theme/icons/index.js
  packages/apollos-ui-prayer/src/PrayerFeature/AvatarList/AvatarList.stories.js
  packages/apollos-ui-prayer/src/PrayerFeature/AvatarList/AvatarList.tests.js
  packages/apollos-ui-prayer/src/PrayerFeature/AvatarList/__snapshots__/AvatarList.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerFeature/AvatarList/index.js
  packages/apollos-ui-prayer/src/PrayerFeature/PrayerFeature.stories.js
  packages/apollos-ui-prayer/src/PrayerFeature/PrayerFeature.tests.js
  packages/apollos-ui-prayer/src/PrayerFeature/__snapshots__/PrayerFeature.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerFeature/index.js
Labels: merge, reviewed

#1471 Move AvatarList component to ui-kit package
  packages/apollos-ui-kit/src/Avatar/Avatar.js
  packages/apollos-ui-kit/src/Avatar/AvatarList/AvatarList.stories.js
  packages/apollos-ui-kit/src/Avatar/AvatarList/AvatarList.tests.js
  packages/apollos-ui-kit/src/Avatar/AvatarList/__snapshots__/AvatarList.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/AvatarList/index.js
  packages/apollos-ui-kit/src/Avatar/index.js
  packages/apollos-ui-prayer/src/PrayerFeature/PrayerFeature.stories.js
  packages/apollos-ui-prayer/src/PrayerFeature/PrayerFeature.tests.js
  packages/apollos-ui-prayer/src/PrayerFeature/__snapshots__/PrayerFeature.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerFeature/index.js
Labels: merge, reviewed

#1462 Prayer api
  README.md
  packages/apollos-data-connector-onesignal/src/data-source.js
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/index.js
  packages/apollos-data-connector-rock/src/interactions/data-source.js
  packages/apollos-data-connector-rock/src/prayer-request/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/prayer-request/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/prayer-request/data-source.js
  packages/apollos-data-connector-rock/src/prayer-request/index.js
  packages/apollos-data-connector-rock/src/prayer-request/resolver.js
  packages/apollos-data-schema/src/index.js
  yarn.lock
Labels: merge

#1476 v1.4.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1484 Reduces Algolia calls
  packages/apollos-data-connector-algolia-search/__mocks__/@apollosproject/config.js
  packages/apollos-data-connector-algolia-search/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
Labels: merge

#1486 Removes interaction sessions
  packages/apollos-data-connector-rock/src/interactions/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/interactions/data-source.js
Labels: merge

#1487 Adds core support for URL type and opening URLs Actions in w/ Features
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/getActionListFeature.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/getHeroListFeature.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/getHorizontalCardListFeature.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/getVerticalCardListFeature.js
  packages/apollos-ui-fragments/src/features.js
Labels: reviewed

#1488 Hero list primary action
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/__snapshots__/HeroListFeatureConnected.tests.js.snap
  packages/apollos-ui-fragments/src/features.js
  packages/apollos-ui-kit/src/ActionList/ActionList.stories.js
  packages/apollos-ui-kit/src/ActionList/ActionList.tests.js
  packages/apollos-ui-kit/src/ActionList/__snapshots__/ActionList.tests.js.snap
  packages/apollos-ui-kit/src/ActionList/index.js
Labels: ready for review

#1492 Adds action list primary action support (a nice wide button)
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/ActionListFeature.tests.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/__snapshots__/ActionListFeatureConnected.tests.js.snap
  packages/apollos-ui-fragments/src/features.js
Labels: merge

#1493 v1.4.3
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1494 Pass schema info to resolving methods
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/model.js
Labels: ready for review

#1495 Adds action list event icons, ported from ActionListCard event icons
  packages/apollos-ui-kit/__mocks__/react-native-safe-area-context.js
  packages/apollos-ui-kit/babel.config.js
  packages/apollos-ui-kit/src/ActionList/ActionList.stories.js
  packages/apollos-ui-kit/src/ActionList/ActionList.tests.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListImage.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.stories.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.tests.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionList/ActionListItem/index.js
  packages/apollos-ui-kit/src/ActionList/__snapshots__/ActionList.tests.js.snap
  packages/apollos-ui-kit/src/ActionList/index.js
Labels: merge
