Repository ApollosProject/apollos-apps, pull requests merged in 2020-03, with the labels that each got.

#1364 Update for UIWebView Deprecation
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/user-web-browser/__tests__/__snapshots__/BrowserWithUserCookie.tests.js.snap
  yarn.lock
Labels: merge

#1369 Added a readme to uikit
  packages/apollos-ui-kit/README.md
Labels: ready for review

#1351 Abstracts Device Type ID
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-rock/src/personal-devices/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/personal-devices/data-source.js
Labels: merge

#1370 Remove headers from summary
  packages/apollos-data-connector-rock/src/content-items/data-source.js
Labels: merge

#1367 Adds more structure to theme overrides
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apolloschurchapp/src/theme/propOverrides.js
  packages/apolloschurchapp/src/theme/styleOverrides.js
  packages/apolloschurchapp/src/theme/theme.js
Labels: merge

#1366 fix isLoading story not showing up in storybook
  packages/apollos-ui-kit/src/typography/headings.stories.js
Labels: merge

#1373 Release 1.3.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1375 Switch from `yarn link` to `yalc` for API packages.
  package.json
  scripts/watch.js
  yarn.lock
Labels: merge

#1354 Allows Configurable Browser
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/index.js
Labels: merge, reviewed

#1380 Added @apollosproject/eslint-config package
  .eslintrc.js
  package.json
  packages/apollos-eslint-config/api.js
  packages/apollos-eslint-config/client.js
  packages/apollos-eslint-config/index.js
  packages/apollos-eslint-config/package.json
Labels: merge

#1374 Interactions schema
  package.json
  packages/apollos-data-connector-rock/src/interactions/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/interactions/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/interactions/data-source.js
  packages/apollos-data-connector-rock/src/interactions/index.js
  packages/apollos-data-connector-rock/src/interactions/resolver.js
  packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap
  packages/apollos-data-connector-rock/src/rock-constants/__tests__/rock-constants.tests.js
  packages/apollos-data-connector-rock/src/rock-constants/index.js
  packages/apollos-data-schema/src/index.js
  scripts/watch.js
  yarn.lock
Labels: merge

#1381 Updates apollo-server-core so that we can use graphql 14.0.0
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-schema/src/index.js
  packages/apollos-server-core/package.json
  packages/apollos-server-core/src/index.js
  yarn.lock
Labels: merge

#1388 Decrease the cache time for the livestreams query
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardConnected.js
Labels: ready for review

#1383 Moves User Web View to Packages
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/RockAuthedWebView/RockAuthedWebView.stories.js
  packages/apollos-ui-connected/src/RockAuthedWebView/RockAuthedWebView.tests.js
  packages/apollos-ui-connected/src/RockAuthedWebView/__snapshots__/RockAuthedWebView.tests.js.snap
  packages/apollos-ui-connected/src/RockAuthedWebView/index.js
  yarn.lock
Labels: merge

#1386 Adds 'up next' support to GraphQL API
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-connector-rock/src/interactions/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/interactions/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/interactions/data-source.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1390 Safer handling of getting horizontal content item fetch more results
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
Labels: merge

#1391 Allows Custom Liked Feed
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/index.js
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeedConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/__snapshots__/HorizontalLikedContentFeedConnected.tests.js.snap
Labels: merge

#1387 Fixes issue with live video when duration is detected as 0 on the live player
  packages/apollos-ui-media-player/src/MediaPlayer/PlayheadState.js
Labels: merge

#1377 Adds CampaignItems Algorithm
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
Labels: merge

#1389 Adds percentCompleted to ContentSeriesContentItem
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1393 Exports RockAuthedWebView
  packages/apollos-ui-connected/src/RockAuthedWebView/RockAuthedWebView.tests.js
  packages/apollos-ui-connected/src/RockAuthedWebView/index.js
  packages/apollos-ui-connected/src/index.js
Labels: ready for review

#1396 Adds VerticalCardListFeature
  README.md
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: ready for review

#1398 Connected "Up Next" button
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/UpNextButtonConnected.tests.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/__snapshots__/UpNextButtonConnected.tests.js.snap
  packages/apollos-ui-connected/src/UpNextButtonConnected/getContentUpNext.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-fragments/src/content.js
  packages/apollos-ui-kit/src/Icon/Icon.js
Labels: merge

#1402 Empty Cursor Zeroes the Count
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: ready for review

#1401 Add horizontal card list feature
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/content-items/resolver.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge
