Repository ApollosProject/apollos-apps, pull requests merged in 2020-07, with the labels that each got.

#1499 Fix issue where re-renders aren't picked up in StretchyView
  packages/apollos-ui-kit/src/StretchyView/StretchyView.stories.js
  packages/apollos-ui-kit/src/StretchyView/index.ios.js
Labels: merge

#1498 Fix issue when changing "onPress" prop on TouchableScale
  packages/apollos-ui-kit/src/TouchableScale/index.js
Labels: merge

#1504 Adds web support to @apollosproject/eslint-config
  packages/apollos-eslint-config/package.json
  packages/apollos-eslint-config/web.js
Labels: merge

#1503 Make `react-native-safe-area-context` a peer dep
  packages/apollos-ui-kit/package.json
Labels: merge

#1502 Two quick prayer fixes
  packages/apollos-data-connector-rock/src/prayer-request/data-source.js
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-media-player/jest.setup.js
  packages/apollos-ui-prayer/src/PrayerCard/__snapshots__/PrayerCard.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerExperienceConnected/__snapshots__/PrayerExperienceConnected.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerInput/__snapshots__/PrayerInput.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerInput/index.js
  packages/apollos-ui-prayer/src/PrayerView/__snapshots__/PrayerView.tests.js.snap
  packages/apollos-ui-prayer/src/screens/AddPrayerScreenConnected/__snapshots__/AddPrayerScreenConnected.tests.js.snap
Labels: merge

#1496 Fixes Chromecast for Android
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/GoogleCastButton.js
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
Labels: merge

#1234 Adds Device Schema
  local.graphql
  packages/apollos-data-connector-onesignal/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-onesignal/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-onesignal/src/data-source.js
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/resolvers.test.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/resolvers.test.js
  packages/apollos-data-connector-rock/src/personal-devices/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/personal-devices/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/personal-devices/data-source.js
  packages/apollos-data-connector-rock/src/personal-devices/index.js
  packages/apollos-data-connector-rock/src/personal-devices/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: blocked

#1510 Ui-connected override names
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardComponentMapper/index.js
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/WebviewFeature.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/index.js
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/PlayButton.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButton/index.js
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarUpdate/UserAvatarUpdate.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/index.js
Labels: merge

#1509 Ui-auth override names
  packages/apollos-ui-auth/src/BackButton.js
  packages/apollos-ui-auth/src/Entry.js
  packages/apollos-ui-auth/src/Header.js
  packages/apollos-ui-auth/src/styles.js
Labels: merge

#1516 Type safes followings return type
  packages/apollos-data-connector-rock/src/followings/data-source.js
Labels: merge

#1501 Use local storage and a user id to only onboard once
  packages/apollos-ui-kit/src/NavigationService/index.js
  packages/apollos-ui-onboarding/src/index.js
  packages/apollos-ui-onboarding/src/onboardingStatus.js
Labels: merge

#1511 Ui packages override names
  packages/apollos-ui-media-player/src/MediaPlayer/AirPlayButton.js
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/FullscreenPlayer.js
  packages/apollos-ui-media-player/src/MediaPlayer/MediaPlayerSafeLayout.js
  packages/apollos-ui-media-player/src/MediaPlayer/MediaPlayerSpacer.js
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/MediaPlayer/Seeker/Timestamp.js
  packages/apollos-ui-media-player/src/MediaPlayer/Seeker/index.js
  packages/apollos-ui-media-player/src/MediaPlayer/VideoWindow.js
  packages/apollos-ui-media-player/src/tabBarWithMediaSpacer.js
  packages/apollos-ui-onboarding/src/OnboardingSwiper/index.js
  packages/apollos-ui-onboarding/src/Slide/Slide.js
  packages/apollos-ui-onboarding/src/Slide/SlideContent/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/AboutYou.js
  packages/apollos-ui-onboarding/src/slides/AskNotifications/AskNotifications.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinder.js
  packages/apollos-ui-passes/src/AddToAppleWalletButton/index.js
  packages/apollos-ui-passes/src/PassView/Barcode.js
  packages/apollos-ui-passes/src/PassView/Fields/Field.js
  packages/apollos-ui-passes/src/PassView/Fields/index.js
  packages/apollos-ui-passes/src/PassView/index.js
  packages/apollos-ui-passes/src/index.js
  packages/apollos-ui-prayer/src/PrayerCard/index.js
  packages/apollos-ui-prayer/src/PrayerInput/index.js
  packages/apollos-ui-prayer/src/PrayerSwiper/index.js
  packages/apollos-ui-prayer/src/PrayerView/index.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureHTMLView.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureItem.js
  packages/apollos-ui-scripture/src/Scripture/ScriptureList.js
  packages/apollos-ui-scripture/src/Scripture/typography/index.js
Labels: merge

#1507 Aligns eslint web rules with core
  packages/apollos-eslint-config/web.js
Labels: merge

#1518 Pass down isFeatured prop so CardMapper can identify FeaturedCards
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
Labels: ready for review

#1517 MVP of Auth Refresh (instead of error)
  .travis.yml
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/auth/__tests__/index.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1382 Prevent an error from being thrown if a campus doesn't have an image
  .vscode/settings.json
  packages/apollos-apollo-server-env-mock/src/rock-api-mocks/campuses.js
  packages/apollos-data-connector-rock/src/campuses/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-rock/src/campuses/__tests__/resolver.tests.js
  packages/apollos-data-connector-rock/src/campuses/resolver.js
Labels: merge

#1519 Adds isLive support on Highlight and Default cards
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.stories.js
  packages/apollos-ui-kit/src/DefaultCard/DefaultCard.tests.js
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/index.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.stories.js
  packages/apollos-ui-kit/src/HighlightCard/HighlightCard.tests.js
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/index.js
Labels: merge

#1343 Adds Core Navigation Analytics
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-analytics/src/CoreNavigationAnalytics.js
  packages/apollos-ui-analytics/src/index.js
  packages/apollos-ui-prayer/jest.setup.js
  yarn.lock
Labels: merge

#1515 Bugsnag Package
  packages/apollos-bugsnag/.babelrc
  packages/apollos-bugsnag/.npmignore
  packages/apollos-bugsnag/.nvmrc
  packages/apollos-bugsnag/README.md
  packages/apollos-bugsnag/jest.setup.js
  packages/apollos-bugsnag/package.json
  packages/apollos-bugsnag/react-native/index.js
  packages/apollos-bugsnag/src/index.js
  yarn.lock
Labels: merge

#1461 Login consumer updates
  packages/apollos-ui-auth/src/LoginProvider.js
  packages/apollos-ui-auth/src/index.js
Labels: merge
