Repository ApollosProject/apollos-apps, pull requests merged in 2020-04, with the labels that each got.

#1404 Adds export for horizontalContentCardComponentMapper to ui-connected package
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardConnected.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1400 Remove upNext and percentComplete from cache.
  packages/apollos-data-schema/src/index.js
Labels: merge

#1399 Interactions performance improvements using Apollos Plugin
  packages/apollos-data-connector-rock/src/content-items/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/interactions/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/interactions/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/interactions/data-source.js
Labels: merge

#1394 Allows Passing Custom Chip Children
  packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntry.tests.js.snap
  packages/apollos-ui-auth/src/ProfileDetails/__snapshots__/ProfileDetailsEntryConnected.tests.js.snap
  packages/apollos-ui-kit/src/ActionCard/ActionCard.stories.js
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/Chip/Chip.stories.js
  packages/apollos-ui-kit/src/Chip/Chip.tests.js
  packages/apollos-ui-kit/src/Chip/__snapshots__/Chip.tests.js.snap
  packages/apollos-ui-kit/src/Chip/index.js
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
Labels: merge

#1395 Adds Interact when Loaded Component
  local.graphql
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-ui-analytics/src/TrackEventWhenLoaded.js
  packages/apollos-ui-analytics/src/TrackEventWhenLoaded.tests.js
  packages/apollos-ui-analytics/src/__snapshots__/TrackEventWhenLoaded.tests.js.snap
  packages/apollos-ui-connected/src/InteractWhenLoadedConnected/InteractWhenLoadedConnected.tests.js
  packages/apollos-ui-connected/src/InteractWhenLoadedConnected/__snapshots__/InteractWhenLoadedConnected.tests.js.snap
  packages/apollos-ui-connected/src/InteractWhenLoadedConnected/index.js
  packages/apollos-ui-connected/src/InteractWhenLoadedConnected/interactWithNode.js
  packages/apollos-ui-connected/src/index.js
Labels: reviewed

#1403 Dark theme fixes
  packages/apollos-ui-auth/src/Entry.js
  packages/apollos-ui-auth/src/Password/EmailEntryConnected.js
  packages/apollos-ui-auth/src/Password/__snapshots__/EmailEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/Password/__snapshots__/PasswordEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntry.tests.js.snap
  packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/VerificationConnected.tests.js.snap
  packages/apollos-ui-auth/src/__snapshots__/Entry.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/LikedContentFeedConnected/LikedContentFeedConnected.js
  packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap
  packages/apollos-ui-kit/src/Button/Button.js
  packages/apollos-ui-kit/src/Button/Button.stories.js
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/inputs/InputUnderline.js
  packages/apollos-ui-kit/src/inputs/Picker/__snapshots__/Picker.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/styles.js
  packages/apollos-ui-kit/src/inputs/Text/__snapshots__/Text.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/types/dark.js
  packages/apollos-ui-kit/src/theme/types/light.js
  packages/apollos-ui-mapview/src/MapViewConnected/MapViewConnected.js
  packages/apollos-ui-media-player/src/MediaPlayer/MiniControls.js
  packages/apollos-ui-media-player/src/tabBarWithMediaSpacer.js
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskName.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AskName/__snapshots__/AskNameConnected.tests.js.snap
Labels: merge

#1406 Release 1.3.1 beta.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
  yarn.lock
Labels: ready for review

#1405 Refactors Card Labels with Custom Icons
  packages/apollos-ui-kit/src/Card/Label.js
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/index.js
Labels: merge

#1407 Updates CardListItem Features Resolver
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-schema/src/index.js
Labels: merge

#1409 Remove object syntax from JSX
  packages/apollos-ui-auth/src/Password/EmailEntryConnected.js
  packages/apollos-ui-auth/src/SMS/PhoneEntryConnected.js
  packages/apollos-ui-auth/src/SMS/VerificationConnected.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
Labels: merge

#1411 Feature fragments
  packages/apollos-ui-fragments/src/features.js
Labels: merge

#1414 Add command to update stories on yarn start
  package.json
Labels: merge

#1416 Moves VerticalCardListFeature component to ui-connected packages
  packages/apollos-ui-connected/src/VerticalCardListFeature/VerticalCardListFeature.stories.js
  packages/apollos-ui-connected/src/VerticalCardListFeature/VerticalCardListFeature.tests.js
  packages/apollos-ui-connected/src/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeature/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1413 Moves ActionListFeature to ui-connected
  packages/apollos-ui-connected/src/ActionListFeature/ActionListFeature.stories.js
  packages/apollos-ui-connected/src/ActionListFeature/ActionListFeature.tests.js
  packages/apollos-ui-connected/src/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeature/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1415 Move horizontal card list feature to core
  packages/apollos-ui-connected/src/HorizontalCardListFeature/HorizontalCardListFeature.stories.js
  packages/apollos-ui-connected/src/HorizontalCardListFeature/HorizontalCardListFeature.tests.js
  packages/apollos-ui-connected/src/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeature/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1412 Adds CampaignItemListFeature to ui-connected package
  packages/apollos-ui-connected/src/CampaignItemListFeature/CampaignItemListFeature.stories.js
  packages/apollos-ui-connected/src/CampaignItemListFeature/CampaignItemListFeature.tests.js
  packages/apollos-ui-connected/src/CampaignItemListFeature/__snapshots__/CampaignItemListFeature.tests.js.snap
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1408 Updated Shadow Value
  packages/apollos-ui-auth/src/Password/__snapshots__/EmailEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntryConnected.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  packages/apollos-ui-connected/src/CampaignItemListFeature/__snapshots__/CampaignItemListFeature.tests.js.snap
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/ContentSingleFeatures/__snapshots__/ContentSingleFeatures.tests.js.snap
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/__snapshots__/ContentSingleFeaturesConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/__snapshots__/HorizontalLikedContentFeed.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/__snapshots__/HorizontalLikedContentFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/LikedContentFeedConnected/__snapshots__/LikedContentList.tests.js.snap
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/__snapshots__/PlayButton.tests.js.snap
  packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
  packages/apollos-ui-kit/src/ActionBar/__snapshots__/ActionBar.tests.js.snap
  packages/apollos-ui-kit/src/ActionCard/__snapshots__/ActionCard.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/__snapshots__/ActionListCard.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/__snapshots__/Avatar.tests.js.snap
  packages/apollos-ui-kit/src/CampusCard/__snapshots__/CampusCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/CardWrapper/__snapshots__/CardWrapper.tests.js.snap
  packages/apollos-ui-kit/src/Card/CardWrapper/index.js
  packages/apollos-ui-kit/src/Card/ErrorCard/__snapshots__/ErrorCard.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/ContentCard/__snapshots__/ContentCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/HorizontalDefaultCard.stories.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/MediaThumbnail/__snapshots__/MediaThumbnail.tests.js.snap
  packages/apollos-ui-kit/src/TableView/__snapshots__/TableView.tests.js.snap
  packages/apollos-ui-kit/src/ThumbnailCard/__snapshots__/ThumbnailCard.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Picker/__snapshots__/Picker.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/types/dark.js
  packages/apollos-ui-kit/src/theme/types/light.js
  packages/apollos-ui-mapview/src/MapView/__snapshots__/MapView.tests.js.snap
  packages/apollos-ui-mapview/src/MapViewConnected/__snapshots__/MapViewConnected.tests.js.snap
  packages/apollos-ui-media-player/src/MediaPlayer/__snapshots__/FullscreenPlayer.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/LocationFinder/__snapshots__/LocationFinder.tests.js.snap
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
Labels: merge

#1417 Release 1.3.1
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#1420 Adds FeaturesFeedConnected component
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeed.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/getFeedFeatures.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/index.js
  packages/apollos-ui-connected/src/index.js
Labels: merge, reviewed

#1419 Adds User feed algorithm
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
Labels: merge

#1418 Adds live consumer wrapping feed features
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
  packages/apollos-ui-connected/src/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeature/index.js
  packages/apollos-ui-connected/src/VerticalCardListFeature/index.js
Labels: ready for review

#1421 Release 1.4.0 beta.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1422 Adds support for Features to be fetched via their ID
  packages/apollos-data-connector-rock/src/content-items/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/content-items/data-source.js
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-data-connector-rock/src/index.js
Labels: ready for review

#1423 Refactors FeaturedFeedConnected to be a feed of feeds using FlatList
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeed.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/featuresFeedComponentMapper.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/index.js
  packages/apollos-ui-connected/src/index.js
Labels: ready for review

#1426 v1.4.0-beta.1
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1425 Adds Features feed incremental loading
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/ActionListFeature.stories.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/ActionListFeature.tests.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/__snapshots__/ActionListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeatureConnected/getActionListFeature.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/index.js
  packages/apollos-ui-connected/src/CampaignItemListFeature/__snapshots__/CampaignItemListFeature.tests.js.snap
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/featuresFeedComponentMapper.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/getFeedFeatures.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/HorizontalCardListFeature.stories.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/HorizontalCardListFeature.tests.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/__snapshots__/HorizontalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/getHorizontalCardListFeature.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/index.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/VerticalCardListFeature.stories.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/VerticalCardListFeature.tests.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/index.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/__snapshots__/VerticalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/getVerticalCardListFeature.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-fragments/src/features.js
Labels: reviewed

#1429 Extends Auth Token Expiration
  packages/apollos-data-connector-rock/src/auth/token.js
Labels: ready for review

#1430 Fixes Html content doubling issue
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/index.js
Labels: merge

#1431 Pull new child content items when opening content single
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
Labels: merge

#1427 Refactors ActionListCard to be ActionList component
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/ActionListFeature.tests.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/__snapshots__/ActionListFeature.tests.js.snap
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeature/index.js
  packages/apollos-ui-kit/src/ActionList/ActionList.stories.js
  packages/apollos-ui-kit/src/ActionList/ActionList.tests.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.stories.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/ActionListItem.tests.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/__snapshots__/ActionListItem.tests.js.snap
  packages/apollos-ui-kit/src/ActionList/ActionListItem/index.js
  packages/apollos-ui-kit/src/ActionList/__snapshots__/ActionList.tests.js.snap
  packages/apollos-ui-kit/src/ActionList/index.js
  packages/apollos-ui-kit/src/index.js
Labels: merge

#1432 Adds ability for HTMLView to handle non-http links
  packages/apollos-data-connector-rock/src/sanitize-html.js
  packages/apollos-ui-connected/src/ContentHTMLViewConnected/ContentHTMLViewConnected.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/safeOpenUrl/index.js
  packages/apollos-ui-connected/src/safeOpenUrl/index.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
Labels: merge

#1433 Fix barStyle to be correct for light and dark theme types
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-kit/src/theme/types/dark.js
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
Labels: merge

#1434 Adds CalendarActionImages from Willow and for Willow
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListCard.stories.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListImage.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/ActionListImage.tests.js
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/__snapshots__/ActionListImage.tests.js.snap
  packages/apollos-ui-kit/src/ActionListCard/ActionListItem/index.js
Labels: merge

#1435 v1.4.0-beta.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1440 Fixes crash in search on android
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/styles.js
Labels: merge

#1437 Adds Pull to refetch on Features feed
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.js
  packages/apollos-ui-connected/src/ActionListFeatureConnected/ActionListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
  packages/apollos-ui-connected/src/FeaturesFeedConnected/featuresFeedComponentMapper.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.tests.js
  packages/apollos-ui-kit/src/FeedView/FeedView.tests.js
  packages/apollos-ui-kit/src/FeedView/__snapshots__/FeedView.tests.js.snap
  packages/apollos-ui-kit/src/FeedView/index.js
Labels: reviewed

#1428 Adds HeroListFeature component to ui-connected package
  packages/apollos-ui-connected/src/HeroListFeature/HeroListFeature.stories.js
  packages/apollos-ui-connected/src/HeroListFeature/HeroListFeature.tests.js
  packages/apollos-ui-connected/src/HeroListFeature/__snapshots__/HeroListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HeroListFeature/index.js
  packages/apollos-ui-kit/src/ActionList/ActionListItem/index.js
Labels: merge
