Repository ApollosProject/apollos-apps, pull requests merged in 2020-02, with the labels that each got.

#1320 Adds document detailing performance goals
  PERFORMANCE.md
Labels: merge

#1306 Move UserAvatar to connected package
  packages/apollos-ui-connected/__mocks__/react-native-permissions/index.js
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarConnected.js
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarConnected.tests.js
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarUpdate/UserAvatarUpdate.js
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarUpdate/index.js
  packages/apollos-ui-connected/src/UserAvatarConnected/__snapshots__/UserAvatarConnected.tests.js.snap
  packages/apollos-ui-connected/src/UserAvatarConnected/getUserPhoto.js
  packages/apollos-ui-connected/src/UserAvatarConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/utils/index.js
  packages/apollos-ui-connected/src/utils/uploadPhoto/index.js
  packages/apolloschurchapp/src/tabs/connect/Connect.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/UserAvatarHeader.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/getUserProfile.js
  packages/apolloschurchapp/src/tabs/connect/UserAvatarHeader/index.js
  packages/apolloschurchapp/src/user-settings/ChangeAvatar.js
  packages/apolloschurchapp/src/user-settings/PersonDetails.tests.js
  packages/apolloschurchapp/src/user-settings/PersonalDetails.js
  packages/apolloschurchapp/src/user-settings/index.js
  yarn.lock
Labels: merge

#1322 Increases default cache time to one hour
  packages/apollos-church-api/src/server.js
Labels: merge, ready for review

#1310 Moves HtmlContent to ui-connected
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/ContentHTMLViewConnected/ContentHTMLViewConnected.js
  packages/apollos-ui-connected/src/ContentHTMLViewConnected/getContentItemContent.js
  packages/apollos-ui-connected/src/ContentHTMLViewConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
Labels: merge

#1323 Allows Mapview button text to be configurable
  packages/apollos-ui-mapview/src/MapView/MapView.stories.js
  packages/apollos-ui-mapview/src/MapView/MapView.tests.js
  packages/apollos-ui-mapview/src/MapView/__snapshots__/MapView.tests.js.snap
  packages/apollos-ui-mapview/src/MapView/index.js
Labels: merge

#1325 Adds Algolia Custom Configuration
  packages/apollos-church-api/config.yml
  packages/apollos-data-connector-algolia-search/__mocks__/algoliasearch.js
  packages/apollos-data-connector-algolia-search/src/__tests__/data-source.tests.js
  packages/apollos-data-connector-algolia-search/src/data-source.js
Labels: merge

#1326 Cleaned up animation tests
  packages/apollos-ui-mapview/jest.setup.js
Labels: merge

#1314 Don't cache the user exists query
  packages/apollos-data-schema/src/index.js
Labels: merge

#1324 Removes auth prefetch cache attempt
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge, ready for review

#1327 Fixes another animated test warning
  packages/apolloschurchapp/jest.setup.js
Labels: ready for review

#1330 Adds support for the auth register endpoints to properly accept Gender/Birthdate
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/auth-sms/__tests__/index.js
  packages/apollos-data-connector-rock/src/auth-sms/data-source.js
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/auth/__tests__/index.tests.js
  packages/apollos-data-connector-rock/src/auth/data-source.js
  packages/apollos-data-connector-rock/src/people/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/people/__tests__/data-source.tests.js
  packages/apollos-data-connector-rock/src/people/data-source.js
  packages/apollos-data-connector-rock/src/people/resolver.js
  packages/apollos-data-connector-rock/src/template/data-source.tests.js
Labels: merge, ready for review

#1335 Fixes Videos on iOS
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/package.json
  yarn.lock
Labels: ready for review

#1321 Adds validation for firstName and lastName on the ui-auth screen
  packages/apollos-ui-auth/src/Profile/ProfileEntry.js
  packages/apollos-ui-auth/src/Profile/ProfileEntryConnected.js
  packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntry.tests.js.snap
  packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntryConnected.tests.js.snap
Labels: merge

#1315 Fixes location finder preferring Cincinnati without a location
  packages/apollos-church-api/local.graphql
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-mapview/src/MapView/MapView.tests.js
  packages/apollos-ui-mapview/src/MapView/__snapshots__/MapView.tests.js.snap
  packages/apollos-ui-mapview/src/MapView/index.js
  packages/apollos-ui-onboarding/src/slides/LocationFinder/LocationFinderConnected.js
  packages/apolloschurchapp/src/user-settings/Locations/Locations.tests.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/getCampusLocations.js
  packages/apolloschurchapp/src/user-settings/Locations/index.js
Labels: merge

#1328 Safely gets auth info in the browser
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.stories.js
  packages/apollos-ui-storybook/src/index.js
Labels: merge

#1336 Release 1.3.0 beta.5
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1338 Adds mailto link support
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
Labels: merge

#1119 Sets Missing ENV Variables to null
  packages/apollos-church-api/scripts/generateLocalSchema.sh
  packages/apollos-config/src/attach-env-variables.js
  packages/apollos-data-connector-algolia-search/jest.setup.js
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-algolia-search/src/data-source.js
  packages/apollos-data-connector-algolia-search/src/jobs.js
  packages/apollos-data-connector-twilio/src/data-source.js
  packages/apollos-server-core/src/index.js
  packages/apolloschurchapp/src/client/fragmentTypes.json
Labels: reviewed

#1334 Moves HorizontalContentSeriesFeedConnected to the ui-connected package
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/getContentSeries.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/utils/testUtils.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/ContentTab.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/Devotional.tests.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/ScriptureTab.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/index.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/__snapshots__/HorizontalContentFeed.tests.js.snap
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
Labels: merge

#1341 Removes images from the mocks to fix inconsistent tests
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
Labels: merge

#1305 Fix Android background button issue
  packages/apollos-ui-auth/src/Entry.js
  packages/apollos-ui-auth/src/Password/PasswordEntry.js
  packages/apollos-ui-auth/src/Password/__snapshots__/EmailEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/Password/__snapshots__/PasswordEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/Profile/ProfileEntry.js
  packages/apollos-ui-auth/src/Profile/__snapshots__/ProfileEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/SMS/Verification.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/Verification.tests.js.snap
  packages/apollos-ui-auth/src/SMS/__snapshots__/VerificationConnected.tests.js.snap
  packages/apollos-ui-auth/src/__snapshots__/Entry.tests.js.snap
  packages/apollos-ui-auth/src/styles.js
  packages/apollos-ui-kit/src/Button/Button.js
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/types/light.js
Labels: merge

#1317 Move and refactor MediaControls
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/MediaControlsConnected/MediaControls.js
  packages/apollos-ui-connected/src/MediaControlsConnected/MediaControlsConnected.js
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/PlayButton.js
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/PlayButton.tests.js
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/PlayButtonConnected.js
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/__snapshots__/PlayButton.tests.js.snap
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/index.js
  packages/apollos-ui-connected/src/MediaControlsConnected/WebView.js
  packages/apollos-ui-connected/src/MediaControlsConnected/getContentMedia.js
  packages/apollos-ui-connected/src/MediaControlsConnected/index.js
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarConnected.tests.js
  packages/apollos-ui-connected/src/UserAvatarConnected/__snapshots__/UserAvatarConnected.tests.js.snap
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-media-player/package.json
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
  yarn.lock
Labels: merge

#1346 Ensure animated values are always the same in connected tests
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/__snapshots__/HorizontalLikedContentFeed.tests.js.snap
  packages/apollos-ui-connected/src/MediaControlsConnected/PlayButtonConnected/__snapshots__/PlayButton.tests.js.snap
  packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap
  packages/apollos-ui-connected/src/UserAvatarConnected/UserAvatarConnected.tests.js
  packages/apollos-ui-connected/src/UserAvatarConnected/__snapshots__/UserAvatarConnected.tests.js.snap
Labels: merge

#1339 Fixes ability to swipe down to Auth after logging in
  packages/apolloschurchapp/src/NavigationService.js
  packages/apolloschurchapp/src/ui/Onboarding/index.js
Labels: ready for review

#1349 Release 1.3.0 beta.6
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: ready for review

#1355 Fixes Horizontal Content Series Connected Crash when Loading
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
Labels: merge

#1356 Fixes being forced through register after you have already registered
  packages/apollos-ui-auth/src/LoginProvider.js
Labels: merge

#1353 Adds Auth to External Browser
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
Labels: merge

#1362 Adds background audio playback
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
Labels: merge

#1361 Reduce create theme calls
  packages/apollos-ui-kit/src/theme/mixins.js
Labels: merge

#1360 With theme works with overrides
  packages/apollos-ui-kit/src/theme/__snapshots__/withTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/withTheme.js
  packages/apollos-ui-kit/src/theme/withTheme.tests.js
Labels: merge

#1359 Adds capability to styled overrides; they can now be a function of component props
  packages/apollos-ui-kit/src/styled/__snapshots__/styled.tests.js.snap
  packages/apollos-ui-kit/src/styled/index.js
  packages/apollos-ui-kit/src/styled/styled.tests.js
Labels: merge

#1342 Auth tabs polish
  packages/apollos-ui-auth/src/Entry.js
  packages/apollos-ui-auth/src/Password/__snapshots__/EmailEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/Profile/ProfileEntryConnected.js
  packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.js
  packages/apollos-ui-auth/src/SMS/__snapshots__/PhoneEntryConnected.tests.js.snap
  packages/apollos-ui-auth/src/__snapshots__/Entry.tests.js.snap
  packages/apollos-ui-auth/src/styles.js
Labels: merge
