Repository ApollosProject/apollos-apps, pull requests merged in 2020-01, with the labels that each got.

#1275 Adds ui config to apollos config package
  packages/apollos-config/jest.setup.js
  packages/apollos-config/package.json
  packages/apollos-config/react-native/__tests__/index.tests.js
  packages/apollos-config/react-native/index.js
  packages/apolloschurchapp/index.js
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/metro.config.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/client/cache.js
  packages/apolloschurchapp/src/client/httpLink.js
  yarn.lock
Labels: merge

#1272 Adds Search field polish
  packages/apollos-ui-kit/src/inputs/Search/__snapshots__/Search.tests.js.snap
  packages/apollos-ui-kit/src/inputs/Search/styles.js
  packages/apolloschurchapp/src/tabs/discover/__snapshots__/discover.tests.js.snap
  packages/apolloschurchapp/src/ui/SearchInputHeader/__snapshots__/SearchInputHeader.tests.js.snap
Labels: ready for review

#1268 Pass dates instead of integers to maximum date in date picker
  packages/apollos-ui-kit/src/inputs/DateInput/DateInput.tests.js
  packages/apollos-ui-kit/src/inputs/DateInput/__snapshots__/DateInput.tests.js.snap
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYou.tests.js.snap
  packages/apollos-ui-onboarding/src/slides/AboutYou/__snapshots__/AboutYouConnected.tests.js.snap
Labels: merge

#1278 Fixes StretchyView bug on overscroll effect
  packages/apollos-ui-kit/src/StretchyView/index.android.js
  packages/apollos-ui-kit/src/StretchyView/index.ios.js
  packages/apolloschurchapp/src/content-single/UniversalContentItem/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
  packages/apolloschurchapp/src/event/components.js
Labels: ready for review

#1271 Fixed issue causing `br`'s without parents to crash the app
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
Labels: reviewed

#1280 Add scaffolding for the apollos-ui-connected package
  packages/apollos-ui-connected/README.md
  packages/apollos-ui-connected/babel.config.js
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/metro.config.js
Labels: merge

#1281 Caching documentation
  CACHING.md
Labels: merge

#1282 Fixes being redirected when entering a bad email/password/sms pin.
  packages/apollos-church-api/local.graphql
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/index.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1283 Simplifies pod management with Bundler
  packages/apolloschurchapp/ios/Gemfile
  packages/apolloschurchapp/ios/Gemfile.lock
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/scripts/install_pods.sh
Labels: merge

#1279 Adds Fragments Package
  .eslintrc.js
  packages/apollos-ui-fragments/README.md
  packages/apollos-ui-fragments/babel.config.js
  packages/apollos-ui-fragments/jest.setup.js
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-fragments/src/campus.js
  packages/apollos-ui-fragments/src/content.js
  packages/apollos-ui-fragments/src/features.js
  packages/apollos-ui-fragments/src/index.js
  packages/apollos-ui-fragments/src/live.js
  packages/apollos-ui-fragments/src/pass.js
  packages/apollos-ui-fragments/src/scripture.js
  packages/apollos-ui-fragments/src/user.js
  packages/apollos-ui-onboarding/jest.setup.js
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-onboarding/src/slides/LocationFinder/getUserCampus.js
  packages/apollos-ui-passes/src/getPass.js
  packages/apolloschurchapp/index.js
  packages/apolloschurchapp/jest.setup.js
  packages/apolloschurchapp/loadConfig.js
  packages/apolloschurchapp/metro.config.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/content-feed/getContentFeed.js
  packages/apolloschurchapp/src/content-single/DevotionalContentItem/getScripture.js
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
  packages/apolloschurchapp/src/content-single/Features/getContentItemFeatures.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/getHorizontalContent.js
  packages/apolloschurchapp/src/content-single/MediaControls/getContentMedia.js
  packages/apolloschurchapp/src/content-single/getContentItem.js
  packages/apolloschurchapp/src/live/getLiveContent.js
  packages/apolloschurchapp/src/scripture/getScripture.js
  packages/apolloschurchapp/src/tabs/connect/LikedContentList/__snapshots__/LikedContentList.tests.js.snap
  packages/apolloschurchapp/src/tabs/connect/getLikedContent.js
  packages/apolloschurchapp/src/tabs/connect/getLoginState.js
  packages/apolloschurchapp/src/tabs/connect/getUserProfile.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/getContentChannels.js
  packages/apolloschurchapp/src/tabs/home/__snapshots__/home.tests.js.snap
  packages/apolloschurchapp/src/tabs/home/getCampaignContentItem.js
  packages/apolloschurchapp/src/tabs/home/getUserFeed.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/query.js
  packages/apolloschurchapp/src/ui/LikeContentButtonConnected/updateLikedContent.js
  packages/apolloschurchapp/src/user-settings/Locations/campusChange.js
  packages/apolloschurchapp/src/user-settings/Locations/getCampusLocations.js
  packages/apolloschurchapp/src/user-settings/UserSettings.tests.js
Labels: merge

#1284 Adds caching to requests made to api.bible
  packages/apollos-data-connector-bible/src/data-source.js
Labels: merge, ready for review

#1285 v1.3.0-beta.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/android/app/build.gradle
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/ios/apolloschurchapp-tvOS/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp-tvOSTests/Info.plist
  packages/apolloschurchapp/ios/apolloschurchapp/Info.plist
  packages/apolloschurchapp/ios/apolloschurchappTests/Info.plist
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1287 Move`LiveProvider` & `LiveConsumer` to ui-connected package
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/live/LiveContext.js
  packages/apollos-ui-connected/src/live/getLiveContent.js
  packages/apollos-ui-connected/src/live/index.js
  packages/apolloschurchapp/src/Providers.js
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
  packages/apolloschurchapp/src/ui/ContentCardConnected/ContentCardConnected.js
Labels: merge

#1290 Release v1.3.0 beta.1
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1292 Use default import in root index
  packages/apolloschurchapp/index.js
Labels: bug

#1289 Order Rock data by multiple fields
  packages/apollos-rock-apollo-data-source/src/__tests__/__snapshots__/request-builder.tests.js.snap
  packages/apollos-rock-apollo-data-source/src/__tests__/request-builder.tests.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
Labels: merge

#1294 Changes Auth Error Message
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge, ready for review

#1291 Moves ContentCardConnected into the ui-connected package
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardConnected.js
  packages/apollos-ui-connected/src/ContentCardConnected/contentCardComponentMapper.js
  packages/apollos-ui-connected/src/ContentCardConnected/getContentCard.js
  packages/apollos-ui-connected/src/ContentCardConnected/index.js
  packages/apollos-ui-connected/src/LikedContentFeedConnected/LikedContentFeedConnected.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/ios/Podfile.lock
  packages/apolloschurchapp/src/content-feed/index.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/HorizontalContentFeed.tests.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/DiscoverFeed.tests.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/SearchFeed.tests.js
  packages/apolloschurchapp/src/tabs/discover/discover.tests.js
  packages/apolloschurchapp/src/tabs/home/Home.js
  packages/apolloschurchapp/src/ui/HorizontalContentCardConnected/index.js
  packages/apolloschurchapp/src/ui/SearchCard/index.js
Labels: merge

#1295 Moves HorizontalContentCardConnected into the ui-connected package
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/horizontalContentCardComponentMapper.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/index.js
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/src/content-single/HorizontalContentFeed/index.js
  packages/apolloschurchapp/src/tabs/discover/DiscoverFeed/TileContentFeed.js
Labels: merge, reviewed

#1293 Packagizes the `LikeContentButtonConnected` component in `@apollosproject/ui-connected`
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/jest.setup.js
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/LikeButton.tests.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/__snapshots__/LikeButton.tests.js.snap
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButtonConnected.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButtonConnected.tests.js
  packages/apollos-ui-connected/src/LikeButtonConnected/getLikedContentItem.js
  packages/apollos-ui-connected/src/LikeButtonConnected/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/updateLikeEntity.js
  packages/apollos-ui-connected/src/LikeButtonConnected/updateLikedContent.js
  packages/apollos-ui-connected/src/__mocks__/@react-native-community/async-storage/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/metro.config.js
  packages/apolloschurchapp/src/content-single/ActionContainer/index.js
Labels: merge, reviewed

#1286 Fixes current campus not showing "distance to location"
  packages/apollos-ui-fragments/src/campus.js
  packages/apollos-ui-mapview/src/MapView/index.js
  packages/apolloschurchapp/src/user-settings/Locations/__snapshots__/Locations.tests.js.snap
  packages/apolloschurchapp/src/user-settings/Locations/getCampusLocations.js
Labels: merge

#1297 Remove inactive or archived groups
  packages/apollos-data-connector-rock/src/groups/data-source.js
Labels: merge

#1296 Move ShareContentButtonConnected into the ui-connected package
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButton/ShareContentButton.tests.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButton/__snapshots__/ShareContentButton.tests.js.snap
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButton/index.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButtonConnected.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButtonConnected.tests.js
  packages/apollos-ui-connected/src/ShareButtonConnected/__snapshots__/ShareButtonConnected.tests.js.snap
  packages/apollos-ui-connected/src/ShareButtonConnected/getShareContent.js
  packages/apollos-ui-connected/src/ShareButtonConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/utils/index.js
  packages/apollos-ui-connected/src/utils/share/index.js
  packages/apollos-ui-connected/src/utils/share/share.tests.js
  packages/apolloschurchapp/src/content-single/ActionContainer/index.js
  packages/apolloschurchapp/src/content-single/Features/ScriptureFeature.js
  packages/apolloschurchapp/src/content-single/Features/TextFeature.js
  packages/apolloschurchapp/src/ui/ShareContentButton/ShareContentButton.tests.js
  packages/apolloschurchapp/src/ui/ShareContentButton/index.js
  packages/apolloschurchapp/src/ui/ShareContentButtonConnected/index.js
Labels: merge

#1277 Adds Rock Entity Mapper
  packages/apollos-data-connector-rock/src/rock-constants/__tests__/__snapshots__/rock-constants.tests.js.snap
  packages/apollos-data-connector-rock/src/rock-constants/__tests__/rock-constants.tests.js
  packages/apollos-data-connector-rock/src/rock-constants/index.js
Labels: merge

#1302 Adds persisted cookies
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge, ready for review

#1301 Simplifies Auth Function
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1300 Initial move and rename WebBrowser
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.js
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/RockAuthedWebBrowser.tests.js
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/getRockAuthDetails.js
  packages/apollos-ui-connected/src/RockAuthedWebBrowser/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/src/content-single/MediaControls/index.js
  packages/apolloschurchapp/src/tabs/connect/ActionBar.js
  packages/apolloschurchapp/src/tabs/connect/ActionTable/index.js
  packages/apolloschurchapp/src/testing-control-panel/index.js
  packages/apolloschurchapp/src/ui/WebBrowser/index.js
  packages/apolloschurchapp/src/ui/WebBrowser/index.tests.js
  packages/apolloschurchapp/src/user-settings/index.js
  yarn.lock
Labels: merge

#1298 Improves flexibility of MapView (needed for Willow's app)
  packages/apollos-ui-mapview/src/MapView/index.js
Labels: ready for review

#1304 Clears apollo store instead of reseting store
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-auth/src/Provider.js
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-media-player/src/Provider.js
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-notifications/src/Provider.js
  packages/apollos-ui-onboarding/package.json
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/src/client/index.js
  yarn.lock
Labels: merge, ready for review

#1307 Release 1.3.0 beta.2
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1299 Compresses images from cloudinary using q_auto by default
  packages/apollos-data-connector-cloudinary/src/__tests__/cloudinary.tests.js
  packages/apollos-data-connector-cloudinary/src/cloudinary.js
Labels: merge

#1303 Improves android profile image quality
  packages/apolloschurchapp/src/user-settings/uploadPhoto.js
Labels: merge

#1308 Release 1.3.0 beta.3
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-church-api/apollos.json
  packages/apollos-church-api/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/apolloschurchapp/apollos.json
  packages/apolloschurchapp/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1311 Exports share function
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/utils/share/index.js
Labels: merge

#1313 Removes Polyfill and Adds UI Dependency
  packages/apolloschurchapp/index.js
  packages/apolloschurchapp/package.json
  packages/apolloschurchapp/polyfill.js
Labels: merge

#1309 Moves SearchCard to ui-connected
  packages/apollos-ui-connected/src/SearchCardConnected/SearchCardConnected.tests.js
  packages/apollos-ui-connected/src/SearchCardConnected/__snapshots__/SearchCardConnected.tests.js.snap
  packages/apollos-ui-connected/src/SearchCardConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apolloschurchapp/src/tabs/discover/SearchFeed/index.js
Labels: merge

#1316 Fixes custom theme color references on weekends
  packages/apolloschurchapp/src/content-single/WeekendContentItem/index.js
Labels: merge, ready for review
