Repository ApollosProject/apollos-apps, pull requests merged in 2020-08, with the labels that each got.

#1524 Update updating.md
  UPDATING.md
Labels: ready for review

#1529 Adds Github Actions CI
  .github/workflows/linting.yml
  .github/workflows/unittest.yml
Labels: ready for review

#1528 Convince the theme mixin to ignore null values
  packages/apollos-ui-kit/src/theme/__snapshots__/mixins.tests.js.snap
  packages/apollos-ui-kit/src/theme/mixins.js
  packages/apollos-ui-kit/src/theme/mixins.tests.js
  packages/apollos-ui-kit/src/theme/theme.stories.js
  packages/apollos-ui-passes/src/PassView/__tests__/__snapshots__/PassView.tests.js.snap
Labels: merge, ready for review

#1526 Features should not render if they have no content
  packages/apollos-ui-connected/src/CampaignItemListFeature/index.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeature/index.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/HeroListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/HeroListFeatureConnected/__snapshots__/HeroListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/index.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/__snapshots__/HorizontalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/index.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeatureConnected.tests.js
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/__snapshots__/VerticalCardListFeatureConnected.tests.js.snap
Labels: merge

#1533 v1.5.0
  CHANGELOG.md
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-bugsnag/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge, ready for review

#1534 chore: Adds Conventional Commits rules to merge
  .github/workflows/titles.yml
Labels: ready for review

#1531 perf: Adds keepAlive support to the DataConnectorRock class.
  load-tests/Apollos App Testing.jmx
  packages/apollos-data-connector-rock/__mocks__/@apollosproject/config.js
  packages/apollos-rock-apollo-data-source/src/index.js
Labels: merge, ready for review

#1532 chore: Adds Eslint Config to Yarn Lock
  yarn.lock
Labels: ready for review

#1535 chore: Adds canary release to Github Actions
  .github/workflows/publish.yml
  package.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-bugsnag/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
  scripts/change-log/append-change-log.js
  scripts/change-log/generate-git-log.sh
  scripts/post-release-tag-update.sh
  scripts/update-apollos-version.js
  scripts/update-change-log.sh
Labels: ready for review

#1538 fix: Removes expand Person from invalid cookie auth flow
  README.md
  packages/apollos-data-connector-rock/src/auth/__tests__/__snapshots__/data-source.tests.js.snap
  packages/apollos-data-connector-rock/src/auth/data-source.js
Labels: merge

#1539 chore: Back out yarn.lock change
  yarn.lock
Labels: merge

#1536 feat: Initial draft of included interfaces
  packages/apollos-data-connector-bible/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-data-schema/src/utils.js
  packages/apollos-server-core/src/index.js
  packages/apollos-server-core/src/interfaces/index.js
  packages/apollos-server-core/src/interfaces/resolver.js
  packages/apollos-server-core/src/interfaces/schema.js
Labels: merge
