Repository ApollosProject/apollos-apps, pull requests merged in 2020-09, with the labels that each got.

#1545 feat: Connected Content Node
  packages/apollos-ui-connected/src/ContentNodeConnected/ContentNodeConnected.js
  packages/apollos-ui-connected/src/ContentNodeConnected/ContentNodeConnected.stories.js
  packages/apollos-ui-connected/src/ContentNodeConnected/ContentNodeConnected.tests.js
  packages/apollos-ui-connected/src/ContentNodeConnected/__snapshots__/ContentNodeConnected.tests.js.snap
  packages/apollos-ui-connected/src/ContentNodeConnected/getContentNode.js
  packages/apollos-ui-connected/src/ContentNodeConnected/index.js
  packages/apollos-ui-connected/src/MediaControlsConnected/MediaControlsConnected.js
  packages/apollos-ui-connected/src/MediaControlsConnected/getMedia.js
  packages/apollos-ui-connected/src/MediaControlsConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-fragments/src/content.js
  packages/apollos-ui-fragments/src/index.js
  packages/apollos-ui-fragments/src/interfaces.js
Labels: reviewed

#1550 chore: Publishes Canary Packages
  .github/workflows/publish.yml
Labels: ready for review

#1551 chore: Simplifies CI Node versions
  .github/workflows/linting.yml
  .github/workflows/publish.yml
  .github/workflows/titles.yml
  .github/workflows/unittest.yml
Labels: ready for review

#1553 chore: Move to NPM Packages
  package.json
Labels: ready for review

#1554 chore: Fetches all tags in Canary publish
  .github/workflows/linting.yml
  .github/workflows/publish.yml
  .github/workflows/titles.yml
  .github/workflows/unittest.yml
Labels: ready for review

#1548 feat: ConnectedParentFeed and ConnectedChildFeed
  packages/apollos-ui-connected/src/ContentChildFeedConnected/ContentChildFeed.stories.js
  packages/apollos-ui-connected/src/ContentChildFeedConnected/ContentChildFeedConnected.js
  packages/apollos-ui-connected/src/ContentChildFeedConnected/ContentChildFeedConnected.tests.js
  packages/apollos-ui-connected/src/ContentChildFeedConnected/__snapshots__/ContentChildFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/ContentChildFeedConnected/getContentChildSiblings.js
  packages/apollos-ui-connected/src/ContentChildFeedConnected/index.js
  packages/apollos-ui-connected/src/ContentParentFeedConnected/ContentParentFeed.stories.js
  packages/apollos-ui-connected/src/ContentParentFeedConnected/ContentParentFeed.tests.js
  packages/apollos-ui-connected/src/ContentParentFeedConnected/ContentParentFeedConnected.js
  packages/apollos-ui-connected/src/ContentParentFeedConnected/__snapshots__/ContentParentFeed.tests.js.snap
  packages/apollos-ui-connected/src/ContentParentFeedConnected/getContentParentChildren.js
  packages/apollos-ui-connected/src/ContentParentFeedConnected/index.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/HorizontalContentSeriesFeedConnected.js
  packages/apollos-ui-connected/src/HorizontalFeedConnected.js
  packages/apollos-ui-connected/src/index.js
Labels: merge

#1557 chore: Cleaned up Codecov
  codecov.yml
Labels: merge

#1555 chore: Allows Single Package Release
  package.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-bugsnag/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1558 chore: Moved docs to website
  CACHING.md
  LOAD_TESTING.md
  PERFORMANCE.md
  PUSH.md
  ROCK_SETUP.md
  SEARCH.md
  TERRAFORM.md
  UPDATING.md
  doc-images/bm-0.png
  doc-images/bm-1.png
  doc-images/bm-2.png
  doc-images/bm-3.png
  doc-images/bm-4.png
  doc-images/bm-5.png
  doc-images/cu-step1.png
  doc-images/cu-step2.png
  doc-images/cu-step3.png
  doc-images/cu-step4.png
  doc-images/cu-step5.png
  doc-images/cu-step6.png
  doc-images/cu-step7.png
Labels: merge

#1559 chore: Fixes Canary Publishing 🤞
  .github/workflows/publish.yml
Labels: merge

#1549 feat: Up next button with node
  packages/apollos-ui-connected/src/UpNextButtonConnected/UpNextButtonConnected.stories.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/UpNextButtonConnected.tests.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/__snapshots__/UpNextButtonConnected.tests.js.snap
  packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
  packages/apollos-ui-fragments/src/content.js
Labels: merge, ready for review

#1560 chore: Updates NPM Action
  .github/workflows/publish.yml
Labels: merge

#1556 chore: Cleans up old config files
  .dockerignore
  .vscode/settings.json
  Dockerfile
  api_heroku.tf
  example.terraform.tfvars
  heroku.yml
  load-tests/Apollos App Testing.jmx
Labels: merge

#1552 feat: NodeSingleConnected component.
  packages/apollos-ui-connected/src/ContentCardConnected/getContentCard.js
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/ContentSingleFeaturesConnected.js
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/ContentSingleFeaturesConnected.tests.js
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/__snapshots__/ContentSingleFeaturesConnected.tests.js.snap
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/getContentItemFeatures.js
  packages/apollos-ui-connected/src/NodeSingleConnected/NodeSingleConnected.stories.js
  packages/apollos-ui-connected/src/NodeSingleConnected/index.js
  packages/apollos-ui-connected/src/UpNextButtonConnected/index.js
  packages/apollos-ui-connected/src/testUtils/index.js
  packages/apollos-ui-fragments/src/interfaces.js
Labels: merge, ready for review

#1561 chore: Trying Another Publish thing...
  .github/workflows/publish.yml
  lerna.json
  packages/apollos-eslint-config/package.json
Labels: ready for review

#1562 chore: Removes Eslint Graphql Plugin
  .graphqlconfig
  local.graphql
  package.json
  packages/apollos-eslint-config/client.js
  packages/apollos-eslint-config/package.json
  packages/apollos-eslint-config/web.js
  scripts/debugTravis.sh
Labels: ready for review

#1565 feat: Adds open_node action to schema
  packages/apollos-data-schema/src/index.js
Labels: merge

#1564 feat: Upgrades Church Online to GraphQL Endpoint
  packages/apollos-data-connector-church-online/src/__tests__/__snapshots__/resolver.tests.js.snap
  packages/apollos-data-connector-church-online/src/__tests__/resolver.tests.js
  packages/apollos-data-connector-church-online/src/data-source.js
Labels: ready for review

#1563 feat: ContentCardConnected stories.
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardConnected.stories.js
  packages/apollos-ui-connected/src/testUtils/index.js
Labels: merge, ready for review

#1567 fix: Added missing node-single export
  packages/apollos-ui-connected/src/index.js
Labels: merge, ready for review

#1566 chore: Updates Onesignal Dependency
  packages/apollos-ui-notifications/package.json
  yarn.lock
Labels: merge

#1572 chore: Publishes to NPM and GPR
  .github/workflows/publish.yml
  lerna.json
  packages/apollos-apollo-server-env-mock/package.json
  packages/apollos-bugsnag/package.json
  packages/apollos-config/package.json
  packages/apollos-data-connector-algolia-search/package.json
  packages/apollos-data-connector-analytics/package.json
  packages/apollos-data-connector-bible/package.json
  packages/apollos-data-connector-church-online/package.json
  packages/apollos-data-connector-cloudinary/package.json
  packages/apollos-data-connector-onesignal/package.json
  packages/apollos-data-connector-passes/package.json
  packages/apollos-data-connector-redis-cache/package.json
  packages/apollos-data-connector-rock/package.json
  packages/apollos-data-connector-twilio/package.json
  packages/apollos-data-schema/package.json
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/package.json
  packages/apollos-server-core/package.json
  packages/apollos-ui-analytics/package.json
  packages/apollos-ui-auth/package.json
  packages/apollos-ui-connected/package.json
  packages/apollos-ui-fragments/package.json
  packages/apollos-ui-htmlview/package.json
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-mapview/package.json
  packages/apollos-ui-media-player/package.json
  packages/apollos-ui-notifications/package.json
  packages/apollos-ui-onboarding/package.json
  packages/apollos-ui-passes/package.json
  packages/apollos-ui-prayer/package.json
  packages/apollos-ui-scripture/package.json
  packages/apollos-ui-storybook/package.json
  packages/babel-preset-apollos/package.json
Labels: merge

#1571 fix: Fast refresh fix for apollos storybook
  ApollosStorybook/metro.config.js
  ApollosStorybook/package.json
  ApollosStorybook/yarn.lock
Labels: merge, ready for review

#1573 chore: Adds Prerelease Command
  package.json
Labels: merge, ready for review

#1574 chore: Update the README
  README.md
Labels: ready for review

#1575 feat: LikeButtonConnected supports Nodes and ContentItems
  ApollosStorybook/App.js
  ApollosStorybook/src/Providers.js
  packages/apollos-data-connector-rock/src/followings/__tests__/__snapshots__/resolvers.tests.js.snap
  packages/apollos-data-connector-rock/src/followings/__tests__/resolvers.tests.js
  packages/apollos-data-connector-rock/src/followings/data-source.js
  packages/apollos-data-connector-rock/src/followings/resolver.js
  packages/apollos-data-schema/src/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButton/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButtonConnected.js
  packages/apollos-ui-connected/src/LikeButtonConnected/LikeButtonConnected.stories.js
  packages/apollos-ui-connected/src/LikeButtonConnected/getLikedContentItem.js
  packages/apollos-ui-connected/src/LikeButtonConnected/getLikedNode.js
  packages/apollos-ui-connected/src/LikeButtonConnected/index.js
  packages/apollos-ui-connected/src/LikeButtonConnected/updateLikeEntity.js
  packages/apollos-ui-connected/src/LikeButtonConnected/updateLikeNode.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-connected/src/testUtils/typeDefsMock.js
Labels: merge, ready for review

#1576 chore: Moves Generating Stories
  package.json
Labels: ready for review

#1577 feat: Connected Theme Mixin
  packages/apollos-ui-connected/src/ThemeMixinConnected/ThemeMixinConnected.stories.js
  packages/apollos-ui-connected/src/ThemeMixinConnected/getNodeTheme.js
  packages/apollos-ui-connected/src/ThemeMixinConnected/index.js
  packages/apollos-ui-connected/src/index.js
  packages/apollos-ui-kit/src/theme/mixins.js
Labels: merge, ready for review

#1578 feat: ShareButtonConnected
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/__snapshots__/ContentSingleFeaturesConnected.tests.js.snap
  packages/apollos-ui-connected/src/NodeFeaturesConnected/__snapshots__/NodeFeaturesConnected.tests.js.snap
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButtonConnected.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButtonConnected.stories.js
  packages/apollos-ui-connected/src/ShareButtonConnected/ShareButtonConnected.tests.js
  packages/apollos-ui-connected/src/ShareButtonConnected/getShareContent.js
Labels: merge

#1580 fix: Stop node model returning decoded node id
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/__tests__/model.js
  packages/apollos-server-core/src/node/model.js
Labels: merge, ready for review

#1581 chore: Updates Prerelease Command
  .gitignore
  README.md
  package.json
Labels: ready for review

#1583 chore: Fixes Linter
  .eslintrc.js
  package.json
  packages/apollos-eslint-config/client.js
  packages/apollos-eslint-config/package.json
  packages/apollos-rock-apollo-data-source/src/index.js
  packages/apollos-rock-apollo-data-source/src/request-builder.js
  packages/apollos-server-core/src/utils/index.js
  packages/apollos-ui-auth/src/Entry.js
  packages/apollos-ui-connected/src/ContentSingleFeaturesConnected/ContentSingleFeatures/index.js
  packages/apollos-ui-connected/src/SearchCardConnected/index.js
  packages/apollos-ui-kit/src/Avatar/AvatarList/index.js
  packages/apollos-ui-kit/src/ContentCard/Metrics.js
  packages/apollos-ui-kit/src/TabView/TabBar/Indicator.js
  packages/apollos-ui-kit/src/styled/createStyleSheet.js
  packages/apollos-ui-kit/src/styled/mergeStyles.js
  packages/apollos-ui-passes/src/PassView/Fields/Field.js
  packages/apollos-ui-passes/src/index.js
  packages/apollos-ui-prayer/src/screens/PrayerScreen/index.js
  yarn.lock
Labels: merge

#1579 fix: Stop passing Color object into the Stylesheet
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardComponentMapper/__snapshots__/ContentCardComponentMapper.tests.js.snap
  packages/apollos-ui-connected/src/HeroListFeatureConnected/__snapshots__/HeroListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/__snapshots__/VerticalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-kit/src/Card/__snapshots__/Card.tests.js.snap
  packages/apollos-ui-kit/src/FeaturedCard/__snapshots__/FeaturedCard.tests.js.snap
  packages/apollos-ui-kit/src/HighlightCard/__snapshots__/HighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalHighlightCard/__snapshots__/HorizontalHighlightCard.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/ModalViewHeader.js
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalView.tests.js.snap
  packages/apollos-ui-kit/src/ModalView/__snapshots__/ModalViewHeader.tests.js.snap
  packages/apollos-ui-kit/src/theme/__snapshots__/createTheme.tests.js.snap
  packages/apollos-ui-kit/src/theme/defaultTheme.js
  packages/apollos-ui-mapview/src/Marker/index.js
  packages/apollos-ui-prayer/src/PrayerExperienceConnected/__snapshots__/PrayerExperienceConnected.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerSwiper/__snapshots__/PrayerSwiper.tests.js.snap
  packages/apollos-ui-prayer/src/PrayerSwiper/index.js
Labels: merge

#1582 chore: adds conventional commits flag
  package.json
Labels: merge

#1585 fix: Storybook bringing along RN dep
  ApollosStorybook/metro.config.js
Labels: merge, ready for review

#1587 fix: Included a permissions lib
  ApollosStorybook/ios/Podfile
  ApollosStorybook/ios/Podfile.lock
Labels: merge, ready for review

#1586 feat: Adding withTheme support to the HorizontalCardConnected
  ApollosStorybook/src/theme/theme.js
  packages/apollos-ui-connected/src/ContentChildFeedConnected/__snapshots__/ContentChildFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/ContentParentFeedConnected/__snapshots__/ContentParentFeed.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardComponentMapper/cardMapper.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardComponentMapper/horizontalContentCardComponentMapper.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardComponentMapper/index.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardConnected.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/HorizontalContentCardConnected.stories.js
  packages/apollos-ui-connected/src/HorizontalContentCardConnected/index.js
  packages/apollos-ui-connected/src/HorizontalContentSeriesFeedConnected/__snapshots__/HorizontalContentSeriesFeedConnected.tests.js.snap
Labels: merge, ready for review

#1588 fix: Improve reliability of pull to refetch on feed features
  packages/apollos-ui-connected/src/FeaturesFeedConnected/FeaturesFeedConnected.js
Labels: merge, ready for review

#1589 fix: Adds Auth theme overrides
  packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntry.js
  packages/apollos-ui-auth/src/ProfileDetails/ProfileDetailsEntryConnected.js
Labels: ready for review

#1584 fix: Removes gradient top on default card
  packages/apollos-ui-connected/src/ContentCardConnected/ContentCardComponentMapper/__snapshots__/ContentCardComponentMapper.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/HorizontalCardListFeature/__snapshots__/HorizontalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalCardListFeatureConnected/__snapshots__/HorizontalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/HorizontalLikedContentFeed/__snapshots__/HorizontalLikedContentFeed.tests.js.snap
  packages/apollos-ui-connected/src/HorizontalLikedContentFeedConnected/__snapshots__/HorizontalLikedContentFeedConnected.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/VerticalCardListFeature/__snapshots__/VerticalCardListFeature.tests.js.snap
  packages/apollos-ui-connected/src/VerticalCardListFeatureConnected/__snapshots__/VerticalCardListFeatureConnected.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/__snapshots__/DefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/DefaultCard/index.js
  packages/apollos-ui-kit/src/HorizontalDefaultCard/__snapshots__/HorizontalDefaultCard.tests.js.snap
  packages/apollos-ui-kit/src/HorizontalDefaultCard/index.js
Labels: merge

#1590 fix: Generate feature IDs in the resolvers, rather than in the datasources.
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
  packages/apollos-server-core/src/node/__tests__/__snapshots__/model.js.snap
  packages/apollos-server-core/src/node/__tests__/model.js
  packages/apollos-server-core/src/node/model.js
Labels: merge, ready for review

#1594 chore: Generates Coverage Reports
  .github/workflows/unittest.yml
Labels: ready for review

#1593 feat: Feature caching support.
  packages/apollos-data-connector-rock/src/features/__tests__/__snapshots__/index.js.snap
  packages/apollos-data-connector-rock/src/features/__tests__/index.js
  packages/apollos-data-connector-rock/src/features/data-source.js
  packages/apollos-data-connector-rock/src/features/resolver.js
Labels: merge, ready for review

#1596 fix: Scroll MapView to first campus on load
  packages/apollos-ui-mapview/src/MapView/index.js
  packages/apollos-ui-mapview/src/MapViewConnected/MapViewConnected.stories.js
Labels: merge, ready for review

#1595 fix: AvatarCloud improvements
  packages/apollos-ui-kit/src/Avatar/AvatarCloud/AvatarCloud.stories.js
  packages/apollos-ui-kit/src/Avatar/AvatarCloud/AvatarCloud.tests.js
  packages/apollos-ui-kit/src/Avatar/AvatarCloud/__snapshots__/AvatarCloud.tests.js.snap
  packages/apollos-ui-kit/src/Avatar/AvatarCloud/index.js
Labels: ready for review

#1597 feat: Ordered lists
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.stories.js
  packages/apollos-ui-htmlview/src/HTMLView/HTMLView.tests.js
  packages/apollos-ui-htmlview/src/HTMLView/__snapshots__/HTMLView.tests.js.snap
  packages/apollos-ui-htmlview/src/HTMLView/defaultRenderer.js
  packages/apollos-ui-kit/src/index.js
  packages/apollos-ui-kit/src/typography/OrderedListItem/OrderedListItem.stories.js
  packages/apollos-ui-kit/src/typography/OrderedListItem/OrderedListItem.tests.js
  packages/apollos-ui-kit/src/typography/OrderedListItem/__snapshots__/OrderedListItem.tests.js.snap
  packages/apollos-ui-kit/src/typography/OrderedListItem/index.js
  packages/apollos-ui-kit/src/typography/index.js
Labels: ready for review

#1591 fix: Date picker defaults
  ApollosStorybook/ios/Podfile.lock
  ApollosStorybook/package.json
  ApollosStorybook/yarn.lock
  packages/apollos-ui-kit/package.json
  packages/apollos-ui-kit/src/inputs/DateInput/index.js
  yarn.lock
Labels: merge, ready for review
